// Run: deno test --no-lock --node-modules-dir=none --allow-env supabase/functions/_shared/businessReport.test.ts
// The monthly business report email builds the General Business Report on the server with the app's own shared code
// (_shared/app = src/shared). This runs that code under Deno on a fictional shop: the numbers, the PDF, the data fetch.
import { jsPDF } from "npm:jspdf@4.2.1";
import QRCode from "npm:qrcode@1.5.4";
import { buildGeneralData } from "./app/reportData.js";
import { businessReportSource, businessReportSummary, drawBusinessReport, letterheadFrom } from "./app/businessReport.js";
import { createReportPdfCore } from "./app/reportPdfCore.js";
import { verifyUrl } from "./app/statementPdfLayout.js";

function ok(cond: unknown, msg: string) {
  if (!cond) throw new Error(`ASSERT ${msg}`);
}
const texts = (doc: jsPDF) => (doc.output() as string).match(/\((?:[^()\\]|\\.)*\)\s*Tj/g)
  ?.map((m) => m.replace(/\)\s*Tj$/, "").slice(1).replace(/\\([()\\])/g, "$1")) || [];

const sale = (o: Record<string, unknown>) => ({ type: "in", category: "sale", transaction_date: "2026-10-02", ...o });
const SRC = {
  transactions: [
    sale({ id: "s1", item_name: "Rice 5kg", amount: 8000, quantity: 1, cost_price: 5000 }),
    sale({ id: "s2", category: "credit sale", item_name: "Oil 1L", amount: 3000, quantity: 2, cost_price: 1200 }),
    { id: "e1", type: "out", category: "expense", item_name: "Transport", amount: 700, transaction_date: "2026-10-03" },
    { id: "b1", type: "out", payment_type: "bill_payment", category: "print-airtime", item_name: "MTN PINs", amount: 9700, note: "Value: ₦100 x100", transaction_date: "2026-10-04" },
  ],
  credits: [], debtPayments: [], invoices: [], staffMap: {},
  asoClients: [{ id: "c1", full_name: "Kemi", current_balance: 20000, status: "active" }],
  contributions: [{ id: "a2", aso_client_id: "c1", type: "commission", amount: 1000, status: "completed", created_at: "2026-10-02T09:00:00" }],
  products: [{ id: "p1", product_name: "Rice 5kg", cost_price: 5000, quantity: 3, low_stock_threshold: 5, needs_costing: false }],
};

Deno.test("the General Business Report: numbers and PDF built on the server by the app's code", () => {
  // deno-lint-ignore no-explicit-any
  const data: any = buildGeneralData(SRC as any, "2026-10-01", "2026-10-31");
  ok(data.profit.goods === 3600 && data.profit.ajo === 1000 && data.profit.bills === 300, "profit by source");
  ok(data.profit.net === 4200, `net profit ${data.profit.net}`);
  const summary = businessReportSummary(data);
  ok(summary.length === 8 && summary[3].label === "Net profit" && summary[3].value === "₦4,200.00", "verify figures");

  const ref = "KDR-202611-ABCDEFGH";
  const q = QRCode.create(verifyUrl(ref), { errorCorrectionLevel: "M" });
  const letterhead = letterheadFrom({ business_name: "Adaeze Fresh Mart", business_address: "Shop 14", business_phone: "0803", email: "a@demo.ng" }, null, new Date("2026-11-01T06:00:00Z"));
  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
  const pdf = createReportPdfCore(doc, { title: "Business Report", businessName: letterhead.businessName, period: "1 Oct 2026 – 31 Oct 2026", letterhead, verifyRef: ref },
    { qr: { size: q.modules.size, isDark: (r: number, c: number) => !!q.modules.get(r, c) } });
  drawBusinessReport(pdf, data);
  const t = texts(pdf.getDoc());
  const has = (s: string) => t.some((x) => x.includes(s));
  ok(has("Adaeze Fresh Mart") && has("BUSINESS REPORT") && has("WHERE THE PROFIT CAME FROM"), "letterhead, title, profit ladder");
  ok(has("Generated by KudiAI Track") && has("A product of Amaya & Co. Technologies") && has("Scan to verify"), "verify footer with the QR");
  ok((pdf.getDoc().output() as string).includes(verifyUrl(ref)), "clickable verify link");
});

Deno.test("the data fetch: same tables as the app, every page of a big month", async () => {
  const calls: string[] = [];
  const rows = (table: string, page: number) => table === "transactions"
    ? Array.from({ length: page === 0 ? 1000 : 3 }, (_, i) => sale({ id: `t${page}-${i}`, amount: 1 }))
    : table === "aso_clients" ? (page === 0 ? [{ id: "c1" }] : []) : [];
  // a chainable stand-in for the Supabase client: records filters, answers .range(a, b) with that page of rows
  // deno-lint-ignore no-explicit-any
  const sb: any = {
    from(table: string) {
      const f: string[] = [];
      // deno-lint-ignore no-explicit-any
      const q: any = new Proxy({}, {
        get: (_t, prop: string) => (...args: unknown[]) => {
          if (prop === "range") {
            calls.push(`${table}:${f.join(",")}:${args[0]}`);
            return Promise.resolve({ data: rows(table, Math.floor(Number(args[0]) / 1000)), error: null });
          }
          if (["eq", "gte", "lte", "lt", "in"].includes(prop)) f.push(`${prop}(${args[0]})`);
          return q;
        },
      });
      return q;
    },
  };
  const src = await businessReportSource(sb, "owner-1", { from: "2026-10-01", to: "2026-10-31" });
  ok(src.transactions.length === 1003, `paged past 1000 rows, got ${src.transactions.length}`);
  ok(calls.some((c) => c.startsWith("transactions:eq(user_id),gte(transaction_date),lte(transaction_date):1000")), "transactions for the owner and month, page 2");
  ok(calls.some((c) => c.startsWith("aso_clients:eq(user_id),eq(portal_active)")), "portal Ajo clients, like the app's store");
  ok(calls.some((c) => c.startsWith("ajo_contributions:in(aso_client_id),gte(created_at),lt(created_at)")), "their contributions around the month");
  ok(calls.some((c) => c.startsWith("debt_payments:eq(owner_id)")) && calls.some((c) => c.startsWith("invoices:eq(user_id)")), "debt payments and invoices");
});
