// Run: deno test --no-lock --node-modules-dir=none --allow-env supabase/functions/_shared/statementPdfLayout.test.ts
// The monthly client statement's PDF is built on the server with this copy of the app's statement layout (jsPDF and the
// QR library from npm, the same versions as the app). Fictional client.
import { jsPDF } from "npm:jspdf@4.2.1";
import QRCode from "npm:qrcode@1.5.4";
import {
  monthlyStatementFilename, monthlyStatementSections, monthlyVerifySummary, renderMonthlyStatementPdf, verifyUrl,
} from "./statementPdfLayout.js";

function ok(cond: unknown, msg: string) {
  if (!cond) throw new Error(`ASSERT ${msg}`);
}

const DATA = {
  month: "2026-10",
  generatedAt: "2026-11-01T06:00:00Z",
  savings: {
    client: { name: "Ngozi Eze", membership_number: "AJO-202608-0001", phone: "0801 000 0000", email: "ngozi@demo.ng",
              address: "5 Allen Avenue", lga: "Ikeja", state: "Lagos" },
    business: { name: "Adaeze Fresh Mart", phone: "0803 123 4567", address: "Shop 14, Ikeja" },
    opening: 4800, total_in: 5000, total_out: 2600, closing: 7200,
    entries: [
      { at: "2026-09-30T23:30:00Z", label: "Contribution", ref: "KDT-202610-AAAAAAA3", credit: true, amount: 3000, balance: 7800 },
      { at: "2026-10-05T11:00:00Z", label: "Withdrawal", ref: "KDT-202610-AAAAAAA4", credit: false, amount: 1000, balance: 6800 },
      { at: "2026-10-05T11:00:00Z", label: "Withdrawal Fee", ref: "KDT-202610-AAAAAAA5", credit: false, amount: 100, balance: 6700 },
      { at: "2026-10-20T08:00:00Z", label: "Esusu Payout · Esusu: Market Women Circle", ref: "KDT-202610-AAAAAAA6", credit: true, amount: 2000, balance: 8700 },
      { at: "2026-10-20T08:00:00Z", label: "Esusu Pot Sweep · Esusu: Market Women Circle", ref: "KDT-202610-AAAAAAA7", credit: false, amount: 1500, balance: 7200 },
    ],
  },
  wallet: {
    account: { number: "8012345678", bank: "Wema Bank", name: "KudiAI/Ngozi Eze" },
    opening_kobo: 1000000, in_kobo: 0, out_kobo: 550000, closing_kobo: 450000,
    entries: [
      { at: "2026-09-30T23:30:00Z", source: "ajo_contribution", credit: false, amount_kobo: 300000, balance_after_kobo: 700000, ref: "KDT-202610-BBBBBBB1" },
      { at: "2026-10-31T22:59:00Z", source: "withdrawal", narration: "To GTBank", credit: false, amount_kobo: 250000, balance_after_kobo: 450000, ref: "KDT-202610-BBBBBBB2" },
    ],
  },
};

// jsPDF writes text as "(...) Tj"
const texts = (doc: jsPDF) => (doc.output() as string).match(/\((?:[^()\\]|\\.)*\)\s*Tj/g)
  ?.map((m) => m.replace(/\)\s*Tj$/, "").slice(1).replace(/\\([()\\])/g, "$1")) || [];
const qr = (text: string) => {
  const q = QRCode.create(text, { errorCorrectionLevel: "M" });
  return { size: q.modules.size as number, isDark: (r: number, c: number) => !!q.modules.get(r, c) };
};

Deno.test("monthly statement: summary of both accounts, then savings and wallet in full — header, client, verify footer", () => {
  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "landscape", compress: false });
  const ref = "KDR-202611-ABCDEFGH";
  const { pages } = renderMonthlyStatementPdf(doc, DATA, { font: "helvetica" }, { verify: { ref, qr: qr(verifyUrl(ref)) } });
  const t = texts(doc);
  const has = (s: string) => t.some((x) => x.includes(s));
  const count = (s: string) => t.filter((x) => x.includes(s)).length;
  ok(pages === 3, `summary + savings + wallet pages, got ${pages}`);
  ok(has("MONTHLY STATEMENT") && has("MONTHLY STATEMENT · SAVINGS") && has("MONTHLY STATEMENT · WALLET"), "all three");
  ok(has("October 2026 at a glance") && t.some((x) => /^1 Oct 2026 .{1,3} 31 Oct 2026$/.test(x)), "the month and the period");
  ok(count("KudiAI Track") >= 3 && count("A product of Amaya & Co. Technologies") >= 6, "logo name + product line on every page (header and footer)");
  ok(has("Ngozi Eze") && has("0801 000 0000  ·  ngozi@demo.ng") && has("5 Allen Avenue, Ikeja, Lagos"), "the client's name, contact details and address");
  ok(has("Membership AJO-202608-0001") && has("Savings with Adaeze Fresh Mart") && has("Account 8012345678"), "both accounts");
  ok(has("NGN 4,800.00") && has("NGN 7,200.00") && has("NGN 10,000.00") && has("NGN 4,500.00"), "opening and closing of both");
  ok(count("Generated by KudiAI Track") === 3, "footer on every page");
  ok(count("Verify this statement at ") === 3 && count(ref) >= 6, "verify line + reference on every page (header and footer)");
  ok(count("Scan to verify") === 3 && (doc.output() as string).includes(verifyUrl(ref)), "QR + clickable link");
  ok(has("Page 3 of 3"), "page count");
  ok((doc.output("arraybuffer") as ArrayBuffer).byteLength > 2000, "a real PDF");
});

Deno.test("no wallet: the summary says so; verify figures cover both accounts", () => {
  // deno-lint-ignore no-explicit-any
  const sections = monthlyStatementSections({ ...DATA, wallet: null }) as any[];
  ok(sections.length === 2 && sections[0].kind === "summary", "summary + savings only");
  ok(/don't have a KudiAI wallet/.test(sections[0].panels[1].empty), "wallet panel explains");
  const v = monthlyVerifySummary(DATA);
  ok(v.length === 8 && v[3].value === "₦7,200.00" && v[7].value === "₦4,500.00", "8 figures, as printed with ₦");
  ok(monthlyVerifySummary({ ...DATA, wallet: null }).some((x) => x.value === "No KudiAI wallet"), "no wallet named");
  ok(monthlyStatementFilename("2026-10") === "KudiAI_Statement_October_2026.pdf", "file name");
});

Deno.test("a quiet month still shows its balances", () => {
  const quiet = { ...DATA, savings: { ...DATA.savings, entries: [], total_in: 0, total_out: 0, opening: 7200, closing: 7200 },
                  wallet: { ...DATA.wallet, entries: [], in_kobo: 0, out_kobo: 0, opening_kobo: 450000 } };
  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "landscape", compress: false });
  renderMonthlyStatementPdf(doc, quiet, { font: "helvetica" });
  const t = texts(doc);
  ok(t.some((x) => x.includes("No savings transactions this month.")) && t.some((x) => x.includes("No wallet transactions this month.")), "says so");
  ok(!t.some((x) => x.includes("Verify this statement")), "no reference → no verify block");
});
