import Modal from "./Modal";
import { exportTransactionReceipt, exportCreditStatement, exportAsoStatement } from "../../utils/pdfExport";

const fmtCurrency = (n) =>
  `₦${Number(n || 0).toLocaleString("en-NG", { minimumFractionDigits: 2 })}`;

function ReceiptRow({ label, value, bold }) {
  return (
    <div className="flex items-start justify-between py-2.5 border-b border-slate-100 dark:border-slate-700/60 last:border-0">
      <span className="text-xs font-medium text-slate-400 dark:text-slate-500 flex-shrink-0 w-28">{label}</span>
      <span className={`text-xs text-right flex-1 break-words ${bold ? "font-bold text-slate-800 dark:text-slate-100" : "font-medium text-slate-700 dark:text-slate-200"}`}>
        {value}
      </span>
    </div>
  );
}

function ShareBar({ onWhatsApp, onPDF }) {
  return (
    <div className="grid grid-cols-2 gap-3 mt-5">
      <button
        onClick={onWhatsApp}
        className="py-3 rounded-xl font-bold text-sm flex items-center justify-center gap-2 text-white transition-all active:scale-95"
        style={{ background: "#25D366" }}
      >
        <svg viewBox="0 0 24 24" fill="currentColor" className="w-4 h-4 flex-shrink-0">
          <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/>
        </svg>
        WhatsApp
      </button>
      <button
        onClick={onPDF}
        className="py-3 rounded-xl font-bold text-sm flex items-center justify-center gap-2 bg-slate-800 dark:bg-slate-700 text-white hover:bg-slate-700 dark:hover:bg-slate-600 transition-all active:scale-95"
      >
        <svg viewBox="0 0 24 24" fill="none" className="w-4 h-4 flex-shrink-0" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
          <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3" />
        </svg>
        PDF
      </button>
    </div>
  );
}

/* ── Transaction Receipt ──────────────────────────────────────────── */
export function TransactionReceipt({ txn, profile, onClose }) {
  const isIn = txn.type === "in";

  const shareWhatsApp = () => {
    const biz = profile.business_name || profile.owner_name || "My Business";
    const lines = [
      `🏪 *${biz}*`,
      `📋 *TRANSACTION RECEIPT*`,
      ``,
      `📝 *${txn.item_name || "Transaction"}*`,
      `📅 Date: ${txn.transaction_date}`,
      `${isIn ? "✅" : "🔴"} Type: ${isIn ? "Cash In" : "Cash Out"}`,
      `💵 Amount: *${fmtCurrency(txn.amount)}*`,
      txn.quantity > 1 ? `📦 Quantity: ${txn.quantity}` : null,
      `🏷️ Category: ${txn.category}`,
      `💳 Payment: ${txn.payment_type}`,
      txn.customer_name ? `👤 Customer: ${txn.customer_name}` : null,
      txn.note ? `📌 Note: ${txn.note}` : null,
      ``,
      `_Generated by KudiAI Track_`,
    ].filter(Boolean).join("\n");
    window.open(`https://wa.me/?text=${encodeURIComponent(lines)}`, "_blank");
  };

  return (
    <Modal title="Transaction Receipt" onClose={onClose}>
      {/* Business header */}
      <div className="rounded-2xl overflow-hidden mb-4" style={{ background: "linear-gradient(135deg,#059669 0%,#047857 100%)" }}>
        <div className="px-5 py-4 text-white">
          <p className="text-[10px] font-semibold text-white/60 uppercase tracking-widest">KudiAI Track</p>
          <p className="font-bold text-lg leading-tight mt-0.5">{profile.business_name || profile.owner_name || "My Business"}</p>
          {profile.phone && <p className="text-xs text-white/70 mt-0.5">{profile.phone}</p>}
        </div>
      </div>

      {/* Amount hero */}
      <div className={`text-center py-4 rounded-2xl mb-4 ${isIn ? "bg-green-50 dark:bg-green-900/20" : "bg-red-50 dark:bg-red-900/20"}`}>
        <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400 dark:text-slate-500 mb-1">
          {isIn ? "Cash In" : "Cash Out"}
        </p>
        <p className={`text-3xl font-black tabular ${isIn ? "text-green-600 dark:text-green-400" : "text-red-500 dark:text-red-400"}`}>
          {fmtCurrency(txn.amount)}
        </p>
        <p className="text-xs text-slate-400 dark:text-slate-500 mt-1">{txn.transaction_date}</p>
      </div>

      {/* Details */}
      <div className="mb-1">
        <ReceiptRow label="Item"     value={txn.item_name} bold />
        <ReceiptRow label="Category" value={txn.category} />
        {txn.quantity > 1 && <ReceiptRow label="Quantity" value={txn.quantity} />}
        <ReceiptRow label="Payment"  value={txn.payment_type} />
        {txn.customer_name && <ReceiptRow label="Customer" value={txn.customer_name} />}
        {txn.note && <ReceiptRow label="Note" value={txn.note} />}
      </div>

      <ShareBar
        onWhatsApp={shareWhatsApp}
        onPDF={() => exportTransactionReceipt(txn, profile)}
      />
    </Modal>
  );
}

/* ── Credit Receipt ───────────────────────────────────────────────── */
export function CreditReceipt({ credit, profile, onClose }) {
  const shareWhatsApp = () => {
    const biz = profile.business_name || profile.owner_name || "My Business";
    const lines = [
      `🏪 *${biz}*`,
      `📋 *CREDIT STATEMENT*`,
      ``,
      `👤 *${credit.customer_name}*`,
      credit.phone   ? `📞 Phone: ${credit.phone}`   : null,
      credit.address ? `📍 Address: ${credit.address}` : null,
      ``,
      `💸 Total Owed:   *${fmtCurrency(credit.total_amount)}*`,
      `✅ Amount Paid:   ${fmtCurrency(credit.amount_paid)}`,
      `🔴 Outstanding:  *${fmtCurrency(credit.outstanding)}*`,
      ``,
      `📅 Date Given: ${credit.date_given || "—"}`,
      `⏰ Due Date:   ${credit.due_date   || "—"}`,
      `📊 Status:     ${(credit.status || "").toUpperCase()}`,
      credit.notes ? `📌 Notes: ${credit.notes}` : null,
      ``,
      `_Generated by KudiAI Track_`,
    ].filter(Boolean).join("\n");
    window.open(`https://wa.me/?text=${encodeURIComponent(lines)}`, "_blank");
  };

  const pct = Math.min(100, ((credit.amount_paid || 0) / (credit.total_amount || 1)) * 100);

  return (
    <Modal title="Credit Statement" onClose={onClose}>
      {/* Header */}
      <div className="rounded-2xl overflow-hidden mb-4" style={{ background: "linear-gradient(135deg,#f59e0b 0%,#d97706 100%)" }}>
        <div className="px-5 py-4 text-white">
          <p className="text-[10px] font-semibold text-white/60 uppercase tracking-widest">KudiAI Track</p>
          <p className="font-bold text-lg leading-tight mt-0.5">{profile.business_name || profile.owner_name || "My Business"}</p>
        </div>
      </div>

      {/* Customer + outstanding */}
      <div className="text-center py-4 rounded-2xl mb-4 bg-amber-50 dark:bg-amber-900/20">
        <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400 dark:text-slate-500 mb-1">Outstanding Balance</p>
        <p className="text-3xl font-black tabular text-amber-600 dark:text-amber-400">{fmtCurrency(credit.outstanding)}</p>
        <p className="text-sm font-semibold text-slate-600 dark:text-slate-300 mt-1">{credit.customer_name}</p>
      </div>

      {/* Progress */}
      <div className="mb-4">
        <div className="flex justify-between text-[10px] font-semibold text-slate-400 dark:text-slate-500 mb-1.5">
          <span>Paid {Math.round(pct)}%</span>
          <span>{fmtCurrency(credit.amount_paid)} of {fmtCurrency(credit.total_amount)}</span>
        </div>
        <div className="h-2 bg-slate-100 dark:bg-slate-700 rounded-full overflow-hidden">
          <div className="h-full bg-green-500 rounded-full" style={{ width: `${pct}%` }} />
        </div>
      </div>

      <div className="mb-1">
        {credit.phone   && <ReceiptRow label="Phone"      value={credit.phone} />}
        {credit.address && <ReceiptRow label="Address"    value={credit.address} />}
        <ReceiptRow label="Date Given" value={credit.date_given || "—"} />
        <ReceiptRow label="Due Date"   value={credit.due_date   || "—"} />
        <ReceiptRow label="Status"     value={(credit.status || "").toUpperCase()} bold />
        {credit.notes && <ReceiptRow label="Notes" value={credit.notes} />}
      </div>

      <ShareBar
        onWhatsApp={shareWhatsApp}
        onPDF={() => exportCreditStatement(credit, profile)}
      />
    </Modal>
  );
}

/* ── Aso Receipt ──────────────────────────────────────────────────── */
export function AsoReceipt({ client, profile, onClose }) {
  const shareWhatsApp = () => {
    const biz = profile.business_name || profile.owner_name || "My Business";
    const lines = [
      `🏪 *${biz}*`,
      `📋 *ASO SAVINGS STATEMENT*`,
      ``,
      `👤 *${client.full_name}*`,
      client.phone ? `📞 Phone: ${client.phone}` : null,
      ``,
      `💰 Total Saved:     *${fmtCurrency(client.total_saved)}*`,
      `💸 Total Withdrawn:  ${fmtCurrency(client.total_withdrawn)}`,
      `💵 Current Balance: *${fmtCurrency(client.current_balance)}*`,
      ``,
      `📅 Frequency:   ${client.contribution_frequency}`,
      `💳 Contribution: ${fmtCurrency(client.contribution_amount)}`,
      client.next_contribution_date ? `⏰ Next Due: ${client.next_contribution_date}` : null,
      `📆 Registered: ${client.registration_date || "—"}`,
      ``,
      `_Generated by KudiAI Track_`,
    ].filter(Boolean).join("\n");
    window.open(`https://wa.me/?text=${encodeURIComponent(lines)}`, "_blank");
  };

  return (
    <Modal title="Aso Statement" onClose={onClose}>
      {/* Header */}
      <div className="rounded-2xl overflow-hidden mb-4" style={{ background: "linear-gradient(135deg,#7c3aed 0%,#5b21b6 100%)" }}>
        <div className="px-5 py-4 text-white">
          <p className="text-[10px] font-semibold text-white/60 uppercase tracking-widest">KudiAI Track</p>
          <p className="font-bold text-lg leading-tight mt-0.5">{profile.business_name || profile.owner_name || "My Business"}</p>
        </div>
      </div>

      {/* Balance hero */}
      <div className="text-center py-4 rounded-2xl mb-4 bg-violet-50 dark:bg-violet-900/20">
        <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400 dark:text-slate-500 mb-1">Current Balance</p>
        <p className="text-3xl font-black tabular text-violet-600 dark:text-violet-400">{fmtCurrency(client.current_balance)}</p>
        <p className="text-sm font-semibold text-slate-600 dark:text-slate-300 mt-1">{client.full_name}</p>
      </div>

      <div className="mb-1">
        {client.phone && <ReceiptRow label="Phone"        value={client.phone} />}
        <ReceiptRow label="Total Saved"      value={fmtCurrency(client.total_saved)} bold />
        <ReceiptRow label="Total Withdrawn"  value={fmtCurrency(client.total_withdrawn)} />
        <ReceiptRow label="Frequency"        value={client.contribution_frequency} />
        <ReceiptRow label="Contribution"     value={fmtCurrency(client.contribution_amount)} />
        {client.next_contribution_date && <ReceiptRow label="Next Due" value={client.next_contribution_date} />}
        <ReceiptRow label="Registered"       value={client.registration_date || "—"} />
      </div>

      <ShareBar
        onWhatsApp={shareWhatsApp}
        onPDF={() => exportAsoStatement(client, profile)}
      />
    </Modal>
  );
}
