// Statement PDF — A4 landscape, real vector text, one page per month per account.
//
// Draws every statement PDF: the owner's wallet statement, a client's savings statement, a client's wallet statement,
// and the monthly statement a client is sent (a summary of both accounts, then savings and wallet in full).
//   Header (every page)  KudiAI Track logo + name, the statement's title, period and when it was generated.
//   Holder (first page)  who it is for — name, phone and email, address — and which account.
//   Each month           opening/closing balance, money in/out, every entry with the balance after it, the month's totals.
//   Footer (every page)  "Generated by KudiAI Track · A product of Amaya & Co. Technologies", the verify link with the
//                        statement's reference and a QR code to scan (when a reference was issued), page n of m.
// Times are the stored server timestamps in WAT.
//
// SELF-CONTAINED — no imports, no browser APIs. It is copied byte-for-byte to
// supabase/functions/_shared/statementPdfLayout.js so the PDF attached to the monthly email (built on the server) is
// drawn by exactly the same code as the one downloaded in the app. Edit THIS file, then run
// `node scripts/sync-statement-layout.mjs`; src/__tests__/clientStatements.test.js fails while the copies differ.
// The QR code arrives as a module matrix ({ size, isDark(row, col) }) and is drawn as vector squares.

// ── WAT time (UTC+1 all year — Nigeria has no daylight saving; mirrors src/utils/wat.js) ──
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const LONG_MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
const pad = (n) => String(n).padStart(2, "0");
function toWAT(input) {
  const t = input instanceof Date ? input : new Date(input == null || input === "" ? Date.now() : input);
  if (Number.isNaN(t.getTime())) return null;
  return new Date(t.getTime() + 3600000);
}
function clock(w) {
  let h = w.getUTCHours();
  const ap = h >= 12 ? "PM" : "AM";
  h = h % 12 || 12;
  return `${pad(h)}:${pad(w.getUTCMinutes())}:${pad(w.getUTCSeconds())} ${ap}`;
}
/** "18 Sep 2026, 09:14:32 PM WAT" */
export function formatWAT(input) {
  const w = toWAT(input);
  return w ? `${w.getUTCDate()} ${MONTHS[w.getUTCMonth()]} ${w.getUTCFullYear()}, ${clock(w)} WAT` : "—";
}
/** "18 Sep 2026" */
export function formatWATDate(input) {
  const w = toWAT(input);
  return w ? `${w.getUTCDate()} ${MONTHS[w.getUTCMonth()]} ${w.getUTCFullYear()}` : "—";
}
/** "09:14:32 PM WAT" */
export function formatWATTime(input) {
  const w = toWAT(input);
  return w ? `${clock(w)} WAT` : "—";
}
/** "2026-09" — the WAT calendar month a timestamp falls in */
export function watMonthKey(input) {
  const w = toWAT(input);
  return w ? `${w.getUTCFullYear()}-${pad(w.getUTCMonth() + 1)}` : "";
}
/** "2026-09" -> "September 2026" */
export function monthKeyLabel(key) {
  const [y, m] = String(key || "").split("-");
  const i = Number(m) - 1;
  return LONG_MONTHS[i] ? `${LONG_MONTHS[i]} ${y}` : String(key || "");
}
/** "2026-09-01".."2026-09-30" -> "1 Sep 2026 – 30 Sep 2026" (a single day once) */
export function periodLabel(fromDate, toDate) {
  const d = (ymd) => formatWATDate(`${ymd}T12:00:00+01:00`);
  if (!fromDate && !toDate) return "";
  if (!fromDate || fromDate === toDate) return d(toDate || fromDate);
  return `${d(fromDate)} – ${d(toDate)}`;
}
/** The first and last day of a "YYYY-MM" month. */
export function monthDates(key) {
  const [y, m] = String(key || "").split("-").map(Number);
  const last = new Date(Date.UTC(y, m, 0)).getUTCDate();
  return { fromDate: `${y}-${pad(m)}-01`, toDate: `${y}-${pad(m)}-${pad(last)}` };
}
/** ₦1,234.50 */
export function fmtNaira(n) {
  const [int, dec] = Number(n || 0).toFixed(2).split(".");
  return "₦" + int.replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "." + dec;
}
const naira = (kobo) => fmtNaira(Number(kobo || 0) / 100);
const toKobo = (n) => (n == null || n === "" ? null : Math.round(Number(n) * 100));

/** The address a statement's QR code and verify line point to. */
export function verifyUrl(ref) {
  return `https://kudiai.app/verify?ref=${encodeURIComponent(ref)}`;
}

// ── Entries ───────────────────────────────────────────────────────────────────
// What each wallet entry is called on a statement (same words as the app's receipts — receiptConfig.WALLET_TITLES;
// a test keeps the two equal). Anything else is title-cased from its source.
export const WALLET_SOURCE_TITLES = {
  topup:                 "Wallet Funding",
  sale:                  "Payment Received",
  bill_spend:            "Bill Payment",
  bill_reversal:         "Bill Refund",
  subscription_spend:    "Plan Upgrade",
  subscription_reversal: "Plan Refund",
  withdrawal:            "Transfer",
  withdrawal_reversal:   "Transfer Refund",
  adjustment:            "Wallet Adjustment",
  transfer_fee:          "Transfer Fee",
  cbn_levy:              "CBN Electronic Transfer Levy",
};
export function walletTitle(source) {
  return WALLET_SOURCE_TITLES[source] || String(source || "").replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

const STATUS_NOTE = { pending: "Pending", processing: "Pending", failed: "Failed", reversed: "Reversed" };

/**
 * Wallet entries, oldest first. Accepts wallet_ledger rows (the app) or client_wallet_statement entries (the server).
 * @param titleFor (source) => what the entry is called
 */
export function walletEntries(rows, titleFor = walletTitle) {
  return [...(rows || [])]
    .map((r) => ({ ...r, at: r.at || r.created_at }))
    .filter((r) => r && r.at)
    .sort((a, b) => new Date(a.at) - new Date(b.at))
    .map((r) => {
      const credit = r.credit != null ? !!r.credit : r.direction === "credit";
      const title = titleFor(r.source);
      const narration = String(r.narration || "").trim();
      const note = STATUS_NOTE[r.status];
      const description = [narration && narration.toLowerCase() !== String(title).toLowerCase() ? `${title} · ${narration}` : title, note ? `(${note})` : ""]
        .filter(Boolean).join(" ");
      return {
        at: r.at,
        month: watMonthKey(r.at),
        description,
        ref: r.ref || r.receipt_ref || "",
        credit,
        amountKobo: Math.round(Number(r.amount_kobo || 0)),
        balanceKobo: r.balance_after_kobo == null ? null : Math.round(Number(r.balance_after_kobo)),
      };
    });
}

/** Savings entries from client_savings_statement (naira, with the running balance already worked out on the server). */
export function savingsEntries(rows) {
  return [...(rows || [])]
    .filter((r) => r && r.at)
    .sort((a, b) => new Date(a.at) - new Date(b.at))
    .map((r) => ({
      at: r.at,
      month: watMonthKey(r.at),
      description: r.label || "Savings entry",
      ref: r.ref || "",
      credit: !!r.credit,
      amountKobo: toKobo(r.amount) || 0,
      balanceKobo: toKobo(r.balance),
    }));
}

/**
 * Group entries by WAT month, oldest first, with each month's totals and opening/closing balance.
 * @param openingKobo the balance before the first entry (when known) — otherwise worked back from the first entry
 */
export function groupByMonth(entries, { openingKobo = null } = {}) {
  const months = [];
  for (const e of entries) {
    let m = months[months.length - 1];
    if (!m || m.key !== e.month) { m = { key: e.month, label: monthKeyLabel(e.month), entries: [] }; months.push(m); }
    m.entries.push(e);
  }
  let carry = openingKobo;
  for (const m of months) {
    m.totalInKobo  = m.entries.filter((e) => e.credit).reduce((s, e) => s + e.amountKobo, 0);
    m.totalOutKobo = m.entries.filter((e) => !e.credit).reduce((s, e) => s + e.amountKobo, 0);
    const first = m.entries[0];
    const last  = m.entries[m.entries.length - 1];
    const workedBack = first.balanceKobo == null ? null : first.balanceKobo - (first.credit ? first.amountKobo : -first.amountKobo);
    // A known opening carries month to month (savings); otherwise each month is worked back from its first entry
    // (the wallet, whose every entry stores its balance).
    m.openingKobo = openingKobo != null ? carry : workedBack;
    m.closingKobo = last.balanceKobo != null ? last.balanceKobo
      : m.openingKobo == null ? null : m.openingKobo + m.totalInKobo - m.totalOutKobo;
    carry = m.closingKobo;
  }
  return months;
}

/** One month, even with no entries (a monthly statement still shows the balance). */
export function singleMonth(key, entries, { openingKobo, closingKobo, inKobo, outKobo }) {
  return {
    key, label: monthKeyLabel(key), entries,
    openingKobo: openingKobo == null ? null : Math.round(openingKobo),
    closingKobo: closingKobo == null ? null : Math.round(closingKobo),
    totalInKobo:  inKobo  != null ? Math.round(inKobo)  : entries.filter((e) => e.credit).reduce((s, e) => s + e.amountKobo, 0),
    totalOutKobo: outKobo != null ? Math.round(outKobo) : entries.filter((e) => !e.credit).reduce((s, e) => s + e.amountKobo, 0),
  };
}

// ── Who the statement is for ──────────────────────────────────────────────────
const joinTidy = (parts, sep) => parts.map((p) => String(p || "").trim()).filter(Boolean).join(sep);

/** A client, from client_savings_statement's `client` (+ `business`). */
export function clientHolder(client = {}, business = {}) {
  const street = String(client.address || "").trim();
  // LGA / state only when the address doesn't already say them
  const area = [client.lga, client.state].filter((x) => x && !street.toLowerCase().includes(String(x).trim().toLowerCase()));
  return {
    name: client.name || "",
    contact: joinTidy([client.phone, client.email], "  ·  "),
    address: joinTidy([street, ...area], ", "),
    business,
  };
}
/** A business (the owner's own wallet statement). */
export function businessHolder({ name, phone, email, address } = {}) {
  return { name: name || "", contact: joinTidy([phone, email], "  ·  "), address: address || "" };
}
function savingsAccount(savings) {
  const c = savings?.client || {};
  const b = savings?.business || {};
  return {
    title: "SAVINGS ACCOUNT",
    lines: [c.membership_number ? `Membership ${c.membership_number}` : "", b.name ? `Savings with ${b.name}` : "", b.phone ? `Contact ${b.phone}` : ""].filter(Boolean),
  };
}
export function walletAccount(account = {}) {
  return {
    title: "WALLET ACCOUNT",
    lines: [account.number ? `Account ${account.number}` : "", account.bank, account.name].filter(Boolean),
  };
}

// ── Figures saved with the statement's reference (shown on the verify page) ──
const N = (kobo) => fmtNaira(Number(kobo || 0) / 100);
export function savingsVerifySummary(savings) {
  return [
    savings?.client?.membership_number ? { label: "Membership", value: String(savings.client.membership_number) } : null,
    { label: "Opening balance", value: fmtNaira(savings?.opening) },
    { label: "Money in",        value: fmtNaira(savings?.total_in) },
    { label: "Money out",       value: fmtNaira(savings?.total_out) },
    { label: "Closing balance", value: fmtNaira(savings?.closing) },
    { label: "Transactions",    value: String((savings?.entries || []).length) },
  ].filter(Boolean);
}
/** months: groupByMonth / singleMonth result for the period */
export function walletVerifySummary(months, accountNumber) {
  const first = months[0], last = months[months.length - 1];
  return [
    accountNumber ? { label: "Wallet account", value: String(accountNumber) } : null,
    { label: "Opening balance", value: first && first.openingKobo != null ? N(first.openingKobo) : "—" },
    { label: "Money in",        value: N(months.reduce((s, m) => s + m.totalInKobo, 0)) },
    { label: "Money out",       value: N(months.reduce((s, m) => s + m.totalOutKobo, 0)) },
    { label: "Closing balance", value: last && last.closingKobo != null ? N(last.closingKobo) : "—" },
    { label: "Transactions",    value: String(months.reduce((s, m) => s + m.entries.length, 0)) },
  ].filter(Boolean);
}
export function monthlyVerifySummary(data) {
  const s = data?.savings, w = data?.wallet;
  return [
    { label: "Savings opening", value: fmtNaira(s?.opening) },
    { label: "Savings in",      value: fmtNaira(s?.total_in) },
    { label: "Savings out",     value: fmtNaira(s?.total_out) },
    { label: "Savings closing", value: fmtNaira(s?.closing) },
    ...(w ? [
      { label: "Wallet opening", value: N(w.opening_kobo) },
      { label: "Wallet in",      value: N(w.in_kobo) },
      { label: "Wallet out",     value: N(w.out_kobo) },
      { label: "Wallet closing", value: N(w.closing_kobo) },
    ] : [{ label: "Wallet", value: "No KudiAI wallet" }]),
  ];
}

// ── Drawing ───────────────────────────────────────────────────────────────────
const NAVY  = [15, 28, 69];
const GREEN = [61, 168, 41];
const INK   = [30, 41, 59];
const MUTED = [100, 116, 139];
const HAIR  = [226, 232, 240];
const PANEL = [248, 250, 252];
const WHITE = [255, 255, 255];
const IN_FG  = [15, 123, 62];
const OUT_FG = [185, 28, 28];

const PAGE_W = 297;
const ML = 14;
const MR = 14;
const RIGHT = PAGE_W - MR;
const CW = PAGE_W - ML - MR;
const ROWS_BOTTOM = 179;             // rows and totals stop above the footer
const FOOT_Y = 183.5;

// Column layout (mm from the left margin) — amounts are right-aligned to their column's right edge.
const COL = {
  date:    { x: ML,       w: 38 },
  desc:    { x: ML + 38,  w: 92 },
  ref:     { x: ML + 130, w: 40 },
  in:      { x: ML + 170, w: 30 },
  out:     { x: ML + 200, w: 30 },
  bal:     { x: ML + 230, w: 39 },
};

/** A QR module matrix as vector squares (one rectangle per run of dark modules in a row). */
function drawQr(doc, qr, x, y, size) {
  const n = qr.size;
  const cell = size / n;
  doc.setFillColor(...WHITE);
  doc.rect(x - 1, y - 1, size + 2, size + 2, "F");
  doc.setFillColor(...NAVY);
  for (let r = 0; r < n; r++) {
    let c = 0;
    while (c < n) {
      if (!qr.isDark(r, c)) { c++; continue; }
      let end = c;
      while (end + 1 < n && qr.isDark(r, end + 1)) end++;
      doc.rect(x + c * cell, y + r * cell, (end - c + 1) * cell, cell + 0.02, "F");
      c = end + 1;
    }
  }
}

/**
 * Draw statement sections onto a fresh jsPDF (A4 landscape, mm).
 * @param sections [{ title, period, holder, account, months, emptyText }] or a summary section
 *                 { kind: "summary", title, period, holder, heading, panels: [{ title, sub, rows: [[label, value, tone]], empty }] }
 * @param verify   { ref, qr } — the statement's reference and its QR matrix; omitted when none could be issued
 * @param assets   { logo?, font } — font "helvetica" writes ₦ as "NGN " (the built-in font has no naira sign)
 * @param {any} doc
 * @param {{ sections: any[], generatedAt?: any, verify?: { ref: string, qr?: { size: number, isDark: Function } } | null }} content
 * @param {{ logo?: any, font?: string }} [assets]
 */
export function renderStatementPdf(doc, { sections, generatedAt, verify = null }, { logo = null, font = "helvetica" } = {}) {
  const custom = font !== "helvetica";
  const t = (s) => (custom ? String(s ?? "") : String(s ?? "").replace(/₦/g, "NGN "));
  const setReg  = (size, color = INK) => { doc.setFont(font, "normal"); doc.setFontSize(size); doc.setTextColor(...color); };
  const setBold = (size, color = INK) => { doc.setFont(font, "bold");   doc.setFontSize(size); doc.setTextColor(...color); };
  const setMono = (size, color = INK) => { doc.setFont("courier", "bold"); doc.setFontSize(size); doc.setTextColor(...color); };
  const fit = (s, w) => { const lines = doc.splitTextToSize(t(s), w); return lines.length > 1 ? `${String(lines[0]).replace(/\s+$/, "")}…` : lines[0] || ""; };

  const stamp = formatWAT(generatedAt || new Date());
  let y = 0;
  let firstPage = true;
  const newPage = () => { if (!firstPage) doc.addPage("a4", "landscape"); firstPage = false; };

  const drawHeader = (section) => {
    if (logo) { try { doc.addImage(logo, "PNG", ML, 8.5, 12, 12); } catch (_) { /* decoration only */ } }
    const tx = logo ? ML + 15 : ML;
    setBold(14, NAVY);
    doc.text("KudiAI Track", tx, 14.5);
    setReg(7.5, MUTED);
    doc.text("A product of Amaya & Co. Technologies", tx, 19);
    setBold(11, INK);
    doc.text(section.title || "STATEMENT", RIGHT, 12.5, { align: "right" });
    setReg(8, MUTED);
    if (section.period) doc.text(t(section.period), RIGHT, 17, { align: "right" });
    setReg(7.5, MUTED);
    doc.text(`Generated ${stamp}`, RIGHT, 21, { align: "right" });
    if (verify?.ref) { setMono(7, INK); doc.text(`Ref ${verify.ref}`, RIGHT, 25, { align: "right" }); }
    doc.setFillColor(...GREEN);
    doc.rect(0, 27.5, PAGE_W, 1.2, "F");
  };

  // Who and which account — on the first page of every month / the summary page.
  const drawHolder = (section) => {
    const h = section.holder || {};
    const a = section.account || { title: "", lines: [] };
    doc.setFillColor(...PANEL); doc.setDrawColor(...HAIR); doc.setLineWidth(0.3);
    doc.roundedRect(ML, 32, CW, 24, 2, 2, "FD");
    const lx = ML + 5, rx = ML + CW * 0.56, lw = CW * 0.5 - 8, rw = CW * 0.44 - 6;
    setBold(6.5, MUTED); doc.text("STATEMENT FOR", lx, 37.5);
    setBold(12.5, INK);  doc.text(fit(h.name || "—", lw), lx, 43.5);
    setReg(8, INK);      if (h.contact) doc.text(fit(h.contact, lw), lx, 48.5);
    setReg(8, MUTED);    if (h.address) doc.text(fit(h.address, lw), lx, 53);
    if (a.title) { setBold(6.5, MUTED); doc.text(a.title, rx, 37.5); }
    (a.lines || []).slice(0, 3).forEach((ln, i) => {
      if (i === 0) setBold(9, INK); else setReg(8, INK);
      doc.text(fit(ln, rw), rx, 43.5 + i * 4.9);
    });
    y = 61;
  };

  const drawSummary = (month) => {
    const boxes = [
      ["Opening balance", month.openingKobo == null ? "—" : naira(month.openingKobo), INK],
      ["Money in",        naira(month.totalInKobo),  IN_FG],
      ["Money out",       naira(month.totalOutKobo), OUT_FG],
      ["Closing balance", month.closingKobo == null ? "—" : naira(month.closingKobo), INK],
    ];
    const gap = 4;
    const bw = (CW - gap * 3) / 4;
    boxes.forEach(([label, value, color], i) => {
      const x = ML + i * (bw + gap);
      doc.setFillColor(...WHITE); doc.setDrawColor(...HAIR); doc.setLineWidth(0.3);
      doc.roundedRect(x, y, bw, 15, 2, 2, "FD");
      setReg(7.5, MUTED);
      doc.text(label, x + 4, y + 5.5);
      setBold(11.5, color);
      doc.text(t(value), x + 4, y + 12);
    });
    y += 20;
  };

  const drawTableHead = () => {
    doc.setFillColor(...NAVY);
    doc.rect(ML, y, CW, 7, "F");
    setBold(7.5, WHITE);
    doc.text("DATE & TIME (WAT)", COL.date.x + 2, y + 4.7);
    doc.text("DESCRIPTION", COL.desc.x, y + 4.7);
    doc.text("REFERENCE", COL.ref.x, y + 4.7);
    doc.text("MONEY IN", COL.in.x + COL.in.w - 2, y + 4.7, { align: "right" });
    doc.text("MONEY OUT", COL.out.x + COL.out.w - 2, y + 4.7, { align: "right" });
    doc.text("BALANCE", COL.bal.x + COL.bal.w - 2, y + 4.7, { align: "right" });
    y += 7;
  };

  const continued = (section, month) => {
    doc.addPage("a4", "landscape");
    drawHeader(section);
    setBold(11, INK);
    doc.text(t(`${month.label} (continued)${section.holder?.name ? `  ·  ${section.holder.name}` : ""}`), ML, 36);
    y = 40;
    drawTableHead();
  };

  const drawSummaryPage = (section) => {
    newPage();
    drawHeader(section);
    drawHolder(section);
    setBold(14, INK);
    doc.text(t(section.heading || ""), ML, y + 2);
    y += 7;
    const gap = 6;
    const pw = (CW - gap) / 2;
    const top = y;
    (section.panels || []).slice(0, 2).forEach((p, i) => {
      const x = ML + i * (pw + gap);
      doc.setFillColor(...WHITE); doc.setDrawColor(...HAIR); doc.setLineWidth(0.3);
      doc.roundedRect(x, top, pw, 76, 2.5, 2.5, "FD");
      doc.setFillColor(...(i === 0 ? GREEN : NAVY));
      doc.rect(x, top, 2.2, 76, "F");
      setBold(12, INK); doc.text(t(p.title), x + 8, top + 9);
      setReg(8, MUTED); if (p.sub) doc.text(fit(p.sub, pw - 14), x + 8, top + 14.5);
      if (p.empty) {
        setReg(9.5, MUTED);
        doc.splitTextToSize(t(p.empty), pw - 16).slice(0, 3).forEach((ln, k) => doc.text(ln, x + 8, top + 28 + k * 5));
        return;
      }
      (p.rows || []).forEach(([label, value, tone], k) => {
        const ry = top + 26 + k * 9.5;
        doc.setDrawColor(...HAIR); doc.setLineWidth(0.15);
        if (k > 0) doc.line(x + 8, ry - 6, x + pw - 6, ry - 6);
        setReg(9, MUTED); doc.text(label, x + 8, ry);
        if (tone === "bold") setBold(11, INK);
        else setBold(9.5, tone === "in" ? IN_FG : tone === "out" ? OUT_FG : INK);
        doc.text(t(value), x + pw - 6, ry, { align: "right" });
      });
    });
    setReg(8, MUTED);
    doc.text(t(section.note || "Every transaction, with the balance after it, is on the following pages."), ML, top + 84);
  };

  (sections || []).forEach((section) => {
    if (section.kind === "summary") { drawSummaryPage(section); return; }
    const months = section.months || [];
    if (!months.length) {
      newPage();
      drawHeader(section);
      drawHolder(section);
      setReg(10, MUTED);
      doc.text(t(section.emptyText || "There are no transactions in the selected period."), ML, y + 4);
      return;
    }
    months.forEach((month) => {
      newPage();
      drawHeader(section);
      drawHolder(section);
      setBold(14, INK);
      doc.text(month.label, ML, y + 2);
      y += 6;
      drawSummary(month);
      if (!month.entries.length) {
        setReg(10, MUTED);
        doc.text(t(section.emptyText || "No transactions this month."), ML, y + 6);
        return;
      }
      drawTableHead();

      month.entries.forEach((e, i) => {
        const descLines = (() => { setReg(8); return doc.splitTextToSize(t(e.description), COL.desc.w - 3).slice(0, 2); })();
        const h = Math.max(8.4, 5.6 + (descLines.length - 1) * 3.6);
        if (y + h > ROWS_BOTTOM) continued(section, month);
        if (i % 2 === 1) { doc.setFillColor(250, 251, 253); doc.rect(ML, y, CW, h, "F"); }
        const base = y + 3.9;
        setReg(8, INK);
        doc.text(formatWATDate(e.at), COL.date.x + 2, base);
        setReg(7, MUTED);
        doc.text(formatWATTime(e.at), COL.date.x + 2, base + 3.4);
        setReg(8, INK);
        descLines.forEach((ln, k) => doc.text(ln, COL.desc.x, base + k * 3.6));
        if (e.ref) { setMono(7.2, INK); doc.text(e.ref, COL.ref.x, base); }
        if (e.credit) { setReg(8.5, IN_FG); doc.text(t(naira(e.amountKobo)), COL.in.x + COL.in.w - 2, base, { align: "right" }); }
        else          { setReg(8.5, OUT_FG); doc.text(t(naira(e.amountKobo)), COL.out.x + COL.out.w - 2, base, { align: "right" }); }
        if (e.balanceKobo != null) { setBold(8.5, INK); doc.text(t(naira(e.balanceKobo)), COL.bal.x + COL.bal.w - 2, base, { align: "right" }); }
        else { setReg(8.5, MUTED); doc.text("—", COL.bal.x + COL.bal.w - 2, base, { align: "right" }); }
        y += h;
        doc.setDrawColor(...HAIR); doc.setLineWidth(0.15);
        doc.line(ML, y, RIGHT, y);
      });

      // Totals for the month
      if (y + 11 > ROWS_BOTTOM) continued(section, month);
      doc.setFillColor(...PANEL); doc.setDrawColor(...NAVY); doc.setLineWidth(0.4);
      doc.rect(ML, y + 1, CW, 9, "FD");
      setBold(8.5, INK);
      doc.text(`Total for ${month.label}`, COL.date.x + 2, y + 6.9);
      setBold(8.5, IN_FG);  doc.text(t(naira(month.totalInKobo)),  COL.in.x  + COL.in.w  - 2, y + 6.9, { align: "right" });
      setBold(8.5, OUT_FG); doc.text(t(naira(month.totalOutKobo)), COL.out.x + COL.out.w - 2, y + 6.9, { align: "right" });
      setBold(8.5, INK);
      doc.text(month.closingKobo == null ? "—" : t(naira(month.closingKobo)), COL.bal.x + COL.bal.w - 2, y + 6.9, { align: "right" });
    });
  });

  // Footers, now that the page count is known
  const total = doc.getNumberOfPages();
  const qrSize = 18;
  const qrX = RIGHT - qrSize, qrY = FOOT_Y + 1.5;
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    doc.setDrawColor(...HAIR); doc.setLineWidth(0.3);
    doc.line(ML, FOOT_Y, RIGHT, FOOT_Y);
    setBold(8, NAVY);
    doc.text("Generated by KudiAI Track", ML, FOOT_Y + 5);
    setReg(7.5, MUTED);
    doc.text("A product of Amaya & Co. Technologies", ML, FOOT_Y + 9);
    if (verify?.ref) {
      setReg(7.5, INK);
      const lead = "Verify this statement at ";
      doc.text(lead, ML, FOOT_Y + 13);
      const lx = ML + doc.getTextWidth(lead);
      doc.setTextColor(...GREEN);
      doc.textWithLink("kudiai.app/verify", lx, FOOT_Y + 13, { url: verifyUrl(verify.ref) });
      const rx = lx + doc.getTextWidth("kudiai.app/verify");
      setReg(7.5, INK);
      doc.text("  ·  Ref", rx, FOOT_Y + 13);
      const refX = rx + doc.getTextWidth("  ·  Ref") + 1.2;
      setMono(7, INK);
      doc.text(verify.ref, refX, FOOT_Y + 13);
    }
    setReg(7, MUTED);
    doc.text("Computer generated · valid without signature · support@kudiai.app", ML, FOOT_Y + (verify?.ref ? 17 : 13));
    if (verify?.ref && verify.qr) {
      drawQr(doc, verify.qr, qrX, qrY, qrSize);
      setReg(6.5, MUTED);
      doc.text("Scan to verify", qrX - 3, FOOT_Y + 6, { align: "right" });
      setReg(7.5, INK);
      doc.text(`Page ${p} of ${total}`, qrX - 3, FOOT_Y + 17, { align: "right" });
    } else {
      setReg(7.5, INK);
      doc.text(`Page ${p} of ${total}`, RIGHT, FOOT_Y + 5, { align: "right" });
    }
  }
  return { pages: total };
}

// ── The statements ────────────────────────────────────────────────────────────

/**
 * A wallet statement (the owner's, or a client's from the app) — one wallet section.
 * @param holder  businessHolder(...) / clientHolder(...)
 * @param account { number, bank, name }
 * @param period  "1 Oct 2026 – 3 Oct 2026"
 */
export function walletStatementSections({ entries, holder, account, period }) {
  return [{
    title: "WALLET STATEMENT", period, holder, account: walletAccount(account),
    months: groupByMonth(entries),
    emptyText: "There are no wallet transactions in the selected period.",
  }];
}

/** A client's savings statement for a period (client_savings_statement result). */
export function savingsStatementSections(savings, { period } = {}) {
  const entries = savingsEntries(savings?.entries);
  return [{
    title: "SAVINGS STATEMENT", period,
    holder: clientHolder(savings?.client, savings?.business), account: savingsAccount(savings),
    months: groupByMonth(entries, { openingKobo: toKobo(savings?.opening) }),
    emptyText: "There are no savings transactions in the selected period.",
  }];
}

/**
 * The monthly statement a client is sent (client_statement_data result: { month, savings, wallet }): a first page
 * with both accounts at a glance, then the savings and the wallet in full (a month with no entries still shows its
 * balance). A client without a KudiAI wallet is told so on the first page.
 */
export function monthlyStatementSections(data, { titleFor = walletTitle } = {}) {
  const key = data?.month || "";
  const { fromDate, toDate } = monthDates(key);
  const period = periodLabel(fromDate, toDate);
  const s = data?.savings || {};
  const w = data?.wallet || null;
  const holder = clientHolder(s.client, s.business);
  const sa = savingsAccount(s);
  const wa = w ? walletAccount(w.account) : null;
  const rows = (open, tin, tout, close, count) => [
    ["Opening balance", fmtNaira(open), ""],
    ["Money in", fmtNaira(tin), "in"],
    ["Money out", fmtNaira(tout), "out"],
    ["Closing balance", fmtNaira(close), "bold"],
    ["Transactions", String(count), ""],
  ];
  const sections = [{
    kind: "summary", title: "MONTHLY STATEMENT", period, holder,
    account: { title: "ACCOUNTS", lines: [sa.lines[0] || "Savings", wa ? wa.lines[0] : "No KudiAI wallet", sa.lines[1] || ""].filter(Boolean) },
    heading: `${monthKeyLabel(key)} at a glance`,
    panels: [
      { title: "Savings", sub: sa.lines.slice(0, 2).join("  ·  "),
        rows: rows(s.opening, s.total_in, s.total_out, s.closing, (s.entries || []).length) },
      w ? { title: "Wallet", sub: wa.lines.slice(0, 2).join("  ·  "),
            rows: rows(w.opening_kobo / 100, w.in_kobo / 100, w.out_kobo / 100, w.closing_kobo / 100, (w.entries || []).length) }
        : { title: "Wallet", sub: "KudiAI wallet", empty: "You don't have a KudiAI wallet yet. Open one in the app to pay contributions and bills, and to receive payouts." },
    ],
  }, {
    title: "MONTHLY STATEMENT · SAVINGS", period, holder, account: sa,
    months: [singleMonth(key, savingsEntries(s.entries), {
      openingKobo: toKobo(s.opening), closingKobo: toKobo(s.closing), inKobo: toKobo(s.total_in), outKobo: toKobo(s.total_out),
    })],
    emptyText: "No savings transactions this month.",
  }];
  if (w) {
    sections.push({
      title: "MONTHLY STATEMENT · WALLET", period, holder, account: wa,
      months: [singleMonth(key, walletEntries(w.entries, titleFor), {
        openingKobo: w.opening_kobo, closingKobo: w.closing_kobo, inKobo: w.in_kobo, outKobo: w.out_kobo,
      })],
      emptyText: "No wallet transactions this month.",
    });
  }
  return sections;
}

/**
 * @param {any} doc
 * @param {any} data
 * @param {{ logo?: any, font?: string }} assets
 * @param {{ verify?: { ref: string, qr?: { size: number, isDark: Function } } | null, titleFor?: Function }} [opts]
 */
export function renderMonthlyStatementPdf(doc, data, assets, { verify = null, titleFor } = {}) {
  return renderStatementPdf(doc, { sections: monthlyStatementSections(data, { titleFor }), generatedAt: data?.generatedAt, verify }, assets);
}

/** "KudiAI_Statement_October_2026.pdf" */
export function monthlyStatementFilename(month) {
  return `KudiAI_Statement_${monthKeyLabel(month).replace(/\s+/g, "_")}.pdf`;
}
