// ── Shared KudiAI Report/Statement PDF Engine ─────────────────────────────────
// Single source of truth for every report and statement across the platform.
// Usage:
//   const pdf = await createReportPdf({ title, businessName, period, logoUrl, entityDetails })
//   pdf.addStats([{ label, value, color?, bg? }])
//   pdf.addSectionTitle("Section")
//   pdf.addTable(cols, rows)           // cols: { key, label, w, right?, bold?, color? }
//   pdf.addTotalsBlock(rows)           // rows: { label, value, bold?, highlight?, sep?, green?, red? }
//   pdf.addBarChart(bars)
//   pdf.addEntityPanel(details)        // [{label,value}] — account holder card
//   pdf.addStatement(txns, opts)       // opts: { openingBalance?, totalDebits?, totalCredits? }
//   await pdf.save("filename.pdf")
//
// Owner reports (2026-10-02) pass `letterhead` + `verifyRef` for the receipt-style look:
//   letterhead: { businessName, logoUrl, address, phone, email, generatedAt } — the business's own logo, name, address and
//               contacts on the left; report title, period, generated date-time and reference on the right
//   verifyRef:  "KDR-YYYYMM-XXXXXXXX" — footer on every page: KudiAI logo, "Generated by KudiAI Track · A product of
//               Amaya & Co. Technologies", the verify link and a QR code that opens it (report_verifications table)
// Without them a report keeps the original header/footer (statements elsewhere in the app use that).
// ─────────────────────────────────────────────────────────────────────────────
// The drawing lives in src/shared/reportPdfCore.js (also run on the server for the monthly business report email);
// this file loads the assets in the browser — the KudiAI logo, NotoSans, the business's logo, the verify QR — and saves.

import { savePdf } from "./pdfSave";
import { loadImageAsset, downscaleImage } from "./pdfAssets";
import { qrMatrix } from "./qrMatrix";
import { createReportPdfCore, fmtCurrency, fmtDate, fmtGeneratedAt } from "../shared/reportPdfCore.js";

export { fmtCurrency, fmtDate, fmtGeneratedAt };

async function imgToBase64(url) {
  if (!url) return null;
  try {
    const ctrl = new AbortController();
    const t    = setTimeout(() => ctrl.abort(), 5000);
    const res  = await fetch(url, { signal: ctrl.signal });
    clearTimeout(t);
    if (!res.ok) return null;
    const blob = await res.blob();
    return new Promise(ok => {
      const r = new FileReader();
      r.onloadend = () => ok(r.result);
      r.onerror   = () => ok(null);
      r.readAsDataURL(blob);
    });
  } catch { return null; }
}

async function loadFontBase64(url) {
  try {
    const ctrl = new AbortController();
    const t    = setTimeout(() => ctrl.abort(), 5000);
    const res  = await fetch(url, { signal: ctrl.signal });
    clearTimeout(t);
    if (!res.ok) return null;
    const buf   = await res.arrayBuffer();
    const bytes = new Uint8Array(buf);
    let binary  = "";
    for (let i = 0; i < bytes.byteLength; i++) binary += String.fromCharCode(bytes[i]);
    return btoa(binary);
  } catch { return null; }
}

// ── Factory ───────────────────────────────────────────────────────────────────
export async function createReportPdf(options = {}) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({
    unit: "mm", format: "a4",
    orientation: options.landscape ? "landscape" : "portrait",
  });
  const branded = !!options.letterhead;
  const origin = typeof window !== "undefined" ? window.location.origin : "";
  const [rawAppLogo, fontReg, fontMed, bizLogo] = await Promise.all([
    imgToBase64(`${origin}/logo-tp.png`),
    loadFontBase64(`${origin}/fonts/NotoSans-Regular.ttf`),
    loadFontBase64(`${origin}/fonts/NotoSans-Medium.ttf`),
    branded && options.letterhead.logoUrl ? loadImageAsset(options.letterhead.logoUrl, 300) : Promise.resolve(null),
  ]);
  // the brand logo file is ~1.5 MB: shrink it before embedding (it is printed at 13 mm at most)
  const appLogo = rawAppLogo ? await downscaleImage(rawAppLogo, 160) : null;
  let qr = null;
  if (branded && options.verifyRef) {
    try { qr = qrMatrix(`https://kudiai.app/verify?ref=${encodeURIComponent(options.verifyRef)}`); } catch { /* the printed link still works */ }
  }
  const pdf = createReportPdfCore(doc, options, { appLogo, fontReg, fontMed, bizLogo, qr });

  async function save(filename) {
    pdf.finalize();
    await savePdf(doc, filename || "KudiAITrack_Report.pdf");
  }
  async function getBase64() {
    pdf.finalize();
    return doc.output("datauristring").split(",")[1];
  }
  return { ...pdf, save, getBase64 };
}
