export const STATES = [
  "Abia","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno",
  "Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","FCT","Gombe","Imo",
  "Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos","Nasarawa",
  "Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto","Taraba",
  "Yobe","Zamfara",
];

export const LGAS = {
  "Abia": ["Aba North","Aba South","Arochukwu","Bende","Ikwuano","Isiala Ngwa North","Isiala Ngwa South","Isuikwuato","Obingwa","Ohafia","Osisioma","Ugwunagbo","Ukwa East","Ukwa West","Umuahia North","Umuahia South","Umu Nneochi"],
  "Adamawa": ["Demsa","Fufure","Ganye","Gayuk","Gombi","Grie","Hong","Jada","Lamurde","Madagali","Maiha","Mayo-Belwa","Michika","Mubi North","Mubi South","Numan","Shelleng","Song","Toungo","Yola North","Yola South"],
  "Akwa Ibom": ["Abak","Eastern Obolo","Eket","Esit Eket","Essien Udim","Etim Ekpo","Etinan","Ibeno","Ibesikpo Asutan","Ibiono-Ibom","Ika","Ikono","Ikot Abasi","Ikot Ekpene","Ini","Itu","Mbo","Mkpat-Enin","Nsit-Atai","Nsit-Ibom","Nsit-Ubium","Obot Akara","Okobo","Onna","Oron","Oruk Anam","Udung-Uko","Ukanafun","Uruan","Urue-Offong/Oruko","Uyo"],
  "Anambra": ["Aguata","Awka North","Awka South","Ayamelum","Dunukofia","Ekwusigo","Idemili North","Idemili South","Ihiala","Njikoka","Nnewi North","Nnewi South","Ogbaru","Onitsha North","Onitsha South","Orumba North","Orumba South","Oyi","Anambra East","Anambra West","Anaocha"],
  "Bauchi": ["Alkaleri","Bauchi","Bogoro","Damban","Darazo","Dass","Ganjuwa","Giade","Itas/Gadau","Jama'are","Katagum","Kirfi","Misau","Ningi","Shira","Tafawa Balewa","Toro","Warji","Zaki","Gamawa"],
  "Bayelsa": ["Brass","Ekeremor","Kolokuma/Opokuma","Nembe","Ogbia","Sagbama","Southern Ijaw","Yenagoa"],
  "Benue": ["Ado","Agatu","Apa","Buruku","Gboko","Guma","Gwer East","Gwer West","Katsina-Ala","Konshisha","Kwande","Logo","Makurdi","Obi","Ogbadibo","Ohimini","Oju","Okpokwu","Otukpo","Tarka","Ukum","Ushongo","Vandeikya"],
  "Borno": ["Abadam","Askira/Uba","Bama","Bayo","Biu","Chibok","Damboa","Dikwa","Gubio","Guzamala","Gwoza","Hawul","Jere","Kaga","Kala/Balge","Konduga","Kukawa","Kwaya Kusar","Mafa","Magumeri","Maiduguri","Marte","Mobbar","Monguno","Ngala","Nganzai","Shani"],
  "Cross River": ["Abi","Akamkpa","Akpabuyo","Bakassi","Bekwarra","Biase","Boki","Calabar Municipal","Calabar South","Etung","Ikom","Obanliku","Obubra","Obudu","Odukpani","Ogoja","Yakuur","Yala"],
  "Delta": ["Aniocha North","Aniocha South","Bomadi","Burutu","Ethiope East","Ethiope West","Ika North East","Ika South","Isoko North","Isoko South","Ndokwa East","Ndokwa West","Okpe","Oshimili North","Oshimili South","Patani","Sapele","Udu","Ughelli North","Ughelli South","Ukwuani","Uvwie","Warri North","Warri South","Warri South West"],
  "Ebonyi": ["Abakaliki","Afikpo North","Afikpo South","Ebonyi","Ezza North","Ezza South","Ikwo","Ishielu","Ivo","Izzi","Ohaozara","Ohaukwu","Onicha"],
  "Edo": ["Akoko-Edo","Egor","Esan Central","Esan North-East","Esan South-East","Esan West","Etsako Central","Etsako East","Etsako West","Igueben","Ikpoba-Okha","Oredo","Orhionmwon","Ovia North-East","Ovia South-West","Owan East","Owan West","Uhunmwonde"],
  "Ekiti": ["Ado Ekiti","Efon","Ekiti East","Ekiti South-West","Ekiti West","Emure","Gbonyin","Ido/Osi","Ijero","Ikere","Ikole","Ilejemeje","Irepodun/Ifelodun","Ise/Orun","Moba","Oye"],
  "Enugu": ["Aninri","Awgu","Enugu East","Enugu North","Enugu South","Ezeagu","Igbo Etiti","Igbo Eze North","Igbo Eze South","Isi Uzo","Nkanu East","Nkanu West","Nsukka","Oji River","Udenu","Udi","Uzo-Uwani"],
  "FCT": ["Abaji","Bwari","Gwagwalada","Kuje","Kwali","Municipal Area Council"],
  "Gombe": ["Akko","Balanga","Billiri","Dukku","Funakaye","Gombe","Kaltungo","Kwami","Nafada","Shomgom","Yamaltu/Deba"],
  "Imo": ["Aboh Mbaise","Ahiazu Mbaise","Ehime Mbano","Ezinihitte","Ideato North","Ideato South","Ihitte/Uboma","Ikeduru","Isiala Mbano","Isu","Mbaitoli","Ngor Okpala","Njaba","Nkwerre","Nwangele","Obowo","Oguta","Ohaji/Egbema","Okigwe","Onuimo","Orlu","Orsu","Oru East","Oru West","Owerri Municipal","Owerri North","Owerri West"],
  "Jigawa": ["Auyo","Babura","Biriniwa","Birnin Kudu","Buji","Dutse","Gagarawa","Garki","Gumel","Guri","Gwaram","Gwiwa","Hadejia","Jahun","Kafin Hausa","Kaugama","Kazaure","Kiri Kasama","Kiyawa","Maigatari","Malam Madori","Miga","Ringim","Roni","Sule Tankarkar","Taura","Yankwashi"],
  "Kaduna": ["Birnin Gwari","Chikun","Giwa","Igabi","Ikara","Jaba","Jema'a","Kachia","Kaduna North","Kaduna South","Kagarko","Kajuru","Kaura","Kauru","Kubau","Kudan","Lere","Makarfi","Sabon Gari","Sanga","Soba","Zangon Kataf","Zaria"],
  "Kano": ["Ajingi","Albasu","Bagwai","Bebeji","Bichi","Bunkure","Dala","Dambatta","Dawakin Kudu","Dawakin Tofa","Doguwa","Fagge","Gabasawa","Garko","Garum Mallam","Gaya","Gezawa","Gwale","Gwarzo","Kabo","Kano Municipal","Karaye","Kibiya","Kiru","Kumbotso","Kunchi","Kura","Madobi","Makoda","Minjibir","Nasarawa","Rano","Rimin Gado","Rogo","Shanono","Sumaila","Takai","Tarauni","Tofa","Tsanyawa","Tudun Wada","Ungogo","Warawa","Wudil"],
  "Katsina": ["Bakori","Batagarawa","Batsari","Baure","Bindawa","Charanchi","Dandume","Danja","Dan Musa","Daura","Dutsi","Dutsin-Ma","Faskari","Funtua","Ingawa","Jibia","Kafur","Kaita","Kankara","Kankia","Katsina","Kurfi","Kusada","Mai'Adua","Malumfashi","Mani","Mashi","Matazu","Musawa","Rimi","Sabuwa","Safana","Sandamu","Zango"],
  "Kebbi": ["Aleiro","Arewa","Argungu","Augie","Bagudo","Birnin Kebbi","Bunza","Dandi","Fakai","Gwandu","Jega","Kalgo","Koko/Besse","Maiyama","Ngaski","Sakaba","Shanga","Suru","Wasagu/Danko","Yauri","Zuru"],
  "Kogi": ["Adavi","Ajaokuta","Ankpa","Bassa","Dekina","Ibaji","Idah","Igalamela-Odolu","Ijumu","Kabba/Bunu","Kogi","Lokoja","Mopa-Muro","Ofu","Ogori/Magongo","Okehi","Okene","Olamaboro","Omala","Yagba East","Yagba West"],
  "Kwara": ["Asa","Baruten","Edu","Ekiti","Ifelodun","Ilorin East","Ilorin South","Ilorin West","Irepodun","Isin","Kaiama","Moro","Offa","Oke Ero","Oyun","Pategi"],
  "Lagos": ["Agege","Ajeromi-Ifelodun","Alimosho","Amuwo-Odofin","Apapa","Badagry","Epe","Eti-Osa","Ibeju-Lekki","Ifako-Ijaye","Ikeja","Ikorodu","Kosofe","Lagos Island","Lagos Mainland","Mushin","Ojo","Oshodi-Isolo","Shomolu","Surulere"],
  "Nasarawa": ["Akwanga","Awe","Doma","Karu","Keana","Keffi","Kokona","Lafia","Nasarawa","Nasarawa Egon","Obi","Toto","Wamba"],
  "Niger": ["Agaie","Agwara","Bida","Borgu","Bosso","Chanchaga","Edati","Gbako","Gurara","Katcha","Kontagora","Lapai","Lavun","Magama","Mariga","Mashegu","Mokwa","Moya","Paikoro","Rafi","Rijau","Shiroro","Suleja","Tafa","Wushishi"],
  "Ogun": ["Abeokuta North","Abeokuta South","Ado-Odo/Ota","Egbado North","Egbado South","Ewekoro","Ifo","Ijebu East","Ijebu North","Ijebu North East","Ijebu Ode","Ikenne","Imeko Afon","Ipokia","Obafemi Owode","Odeda","Odogbolu","Ogun Waterside","Remo North","Sagamu"],
  "Ondo": ["Akoko North-East","Akoko North-West","Akoko South-East","Akoko South-West","Akure North","Akure South","Ese Odo","Idanre","Ifedore","Ilaje","Ile Oluji/Okeigbo","Irele","Odigbo","Okitipupa","Ondo East","Ondo West","Ose","Owo"],
  "Osun": ["Atakumosa East","Atakumosa West","Ayedaade","Ayedire","Boluwaduro","Boripe","Ede North","Ede South","Egbedore","Ejigbo","Ife Central","Ife East","Ife North","Ife South","Ifedayo","Ifelodun","Ila","Ilesa East","Ilesa West","Irepodun","Irewole","Isokan","Iwo","Obokun","Odo Otin","Ola Oluwa","Olorunda","Oriade","Orolu","Osogbo"],
  "Oyo": ["Afijio","Akinyele","Atiba","Atisbo","Egbeda","Ibadan North","Ibadan North-East","Ibadan North-West","Ibadan South-East","Ibadan South-West","Ibarapa Central","Ibarapa East","Ibarapa North","Ido","Irepo","Iseyin","Itesiwaju","Iwajowa","Kajola","Lagelu","Ogbomosho North","Ogbomosho South","Ogo Oluwa","Olorunsogo","Oluyole","Ona Ara","Orelope","Ori Ire","Oyo East","Oyo West","Saki East","Saki West","Surulere"],
  "Plateau": ["Barkin Ladi","Bassa","Bokkos","Jos East","Jos North","Jos South","Kanam","Kanke","Langtang North","Langtang South","Mangu","Mikang","Pankshin","Qua'an Pan","Riyom","Shendam","Wase"],
  "Rivers": ["Abua/Odual","Ahoada East","Ahoada West","Akuku-Toru","Andoni","Asari-Toru","Bonny","Degema","Eleme","Emohua","Etche","Gokana","Ikwerre","Khana","Obio-Akpor","Ogba/Egbema/Ndoni","Ogu/Bolo","Okrika","Omuma","Opobo/Nkoro","Oyigbo","Port Harcourt","Tai"],
  "Sokoto": ["Binji","Bodinga","Dange Shuni","Gada","Goronyo","Gudu","Gwadabawa","Illela","Isa","Kebbe","Kware","Rabah","Sabon Birni","Shagari","Silame","Sokoto North","Sokoto South","Tambuwal","Tangaza","Tureta","Wamako","Wurno","Yabo"],
  "Taraba": ["Ardo-Kola","Bali","Donga","Gashaka","Gassol","Ibi","Jalingo","Karim Lamido","Kumi","Lau","Sardauna","Takum","Ussa","Wukari","Yorro","Zing"],
  "Yobe": ["Bade","Bursari","Damaturu","Fika","Fune","Geidam","Gujba","Gulani","Jakusko","Karasuwa","Machina","Nangere","Nguru","Potiskum","Tarmua","Yunusari","Yusufari"],
  "Zamfara": ["Anka","Bakura","Birnin Magaji/Kiyaw","Bukkuyum","Bungudu","Chafe","Gummi","Gusau","Kaura Namoda","Maradun","Maru","Shinkafi","Talata Mafara","Zurmi"],
};

export const WARDS = {
  "Lagos": {
    "Agege": ["Agege Central","Dopemu","Ifako","Isale Oja","Keke","Meiran","Ogba","Oko-Oba","Orile Agege","Tabon-Tabon"],
    "Ajeromi-Ifelodun": ["Ajeromi","Amukoko","Awodi Ora","Ifelodun","Ijora Badia","Layeni","Mosafejo","Olodi-Apapa","Temidire","Tolu"],
    "Alimosho": ["Abule Egba","Ayobo","Egbeda","Idimu","Igando","Iyana Ipaja","Meiran","Orile Agege","Shasha","Akowonjo"],
    "Amuwo-Odofin": ["Amuwo","Festac","Mile 2","Oriade","Satellite Town","Volks","Ago Palace","Kirikiri","Ijegun","Iba"],
    "Apapa": ["Apapa","Olodi","Apapa GRA","Ajegunle","Amukoko","Ijora","Liverpool","Marine","Sari Iganmu","Wharf"],
    "Badagry": ["Ajara","Awhanjigo","Badagry Central","Ibereko","Ikoga","Ilobi","Ipankodo","Iyaafin","Ketu-Ereyun","Topo"],
    "Epe": ["Epe Central","Agbowa","Eredo","Ibeju","Ikosi-Ejinrin","Itoikin","Oriade","Poka","Abomiti","Ejirin"],
    "Eti-Osa": ["Ajah","Ikoyi","Lekki","Victoria Island","Maroko","Eti-Osa East","Ogudu","Oniru","Sangotedo","Jakande"],
    "Ibeju-Lekki": ["Akodo","Ibeju","Lakowe","Lekki","Noforija","Orimedu","Ise","Akodo-Ise","Ibereko","Magbon"],
    "Ifako-Ijaye": ["Agbado","Ifako","Ijaye","Ogba","Ojokoro","Alagbado","Alakuko","Iju-Ishaga","Fagba","Abule Egba"],
    "Ikeja": ["Alausa","Agidingbi","CMD Road","Ikeja GRA","Mobolaji Bank Anthony Way","Oregun","Onigbongbo","Opebi","Palmgrove","Toyin"],
    "Ikorodu": ["Agbowa","Ikorodu Central","Ijede","Imota","Ikorodu North","Ikorodu West","Isiu","Itamaga","Odo-Nla","Parafa"],
    "Kosofe": ["Agboyi","Alapere","Ikosi","Ketu","Kosofe","Ogudu","Ojota","Omole","Mile 12","Shangisha"],
    "Lagos Island": ["Agarawu","Elegbata","Epetedo","Lafiaji","Olowogbowo","Onikan","Sandgrouse","Campos","Idumagbo","Lagos Island Central"],
    "Lagos Mainland": ["Ebute Metta East","Ebute Metta West","Glover","Olaleye","Suru Alaba","Yaba","Adogumejo","Campos","Eleganza","Ojuelegba"],
    "Mushin": ["Apatira","Idi-Oro","Ishagatedo","Mushin","Ojuwoye","Odi-Olowo","Palm Avenue","Oke-Odo","Ladipo","Agege Road"],
    "Ojo": ["Ajangbadi","Ojo Central","Iba","Ilogbo","Isashi","Okokomaiko","Oriade","Shibiri","Tedi","Trade Fair"],
    "Oshodi-Isolo": ["Bolade","Isolo","Mafoluku","Mile 2","Oshodi","Shogunle","Ilasamaja","Ejigbo","Okota","Ago Palace"],
    "Shomolu": ["Bariga","Gbagada","Obanikoro","Pedro","Shomolu","Somolu","Ifako","Oworo","Owode","Ketu"],
    "Surulere": ["Aguda","Alaka","Bode Thomas","Eric Moore","Ijesha","Itire","Kilo","Masha","Ojuelegba","Shitta"],
  },
  "Kano": {
    "Kano Municipal": ["Dala","Fagge","Gwale","Kano Municipal","Nasarawa","Tarauni","Ungogo","Kofar Ruwa","Kurna","Tudun Wada"],
    "Fagge": ["Fagge A","Fagge B","Fagge C","Fagge D","Fagge E","Fagge F","Fagge G","Fagge H","Fagge I","Kabuga"],
    "Dala": ["Dala A","Dala B","Dala C","Goron Dutse","Ja'en","Kofar Mata","Kurna","Nassarawa","Rijiyar Zaki","Dala D"],
    "Gwale": ["Dan Agundi","Dan Iyan","Gwale","Hotoro","Jakara","Kabuga","Kofar Kabuga","Kofar Ruwa","Kurna","Yalwa"],
    "Tarauni": ["Dorayi","Getso","Kabuga","Kofar Nassarawa","Maisandari","Nasarawa","Tarauni","Unguwar Uku","Yamma","Zawachiki"],
    "Ungogo": ["Dawanau","Gama","Gobirawa","Katsina Road","Madobi","Nassarawa","Tarauni","Ungogo","Yankin","Zawachiki"],
    "Nassarawa": ["Bompai","Dan Agundi","Diso","Giginyu","Gwamma","Kabuga","Nasarawa","Rijiyar Lemo","Tarauni","Zango"],
    "Ikeja": ["Alausa","Agidingbi","CMD Road","Ikeja GRA","Mobolaji Bank Anthony Way","Oregun","Onigbongbo","Opebi","Palmgrove","Toyin"],
    "Dambatta": ["Dambatta Central","Dambatta East","Dambatta North","Dambatta South","Dambatta West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Bichi": ["Bichi Central","Bichi East","Bichi North","Bichi South","Bichi West","Danzomo","Diso","Gama","Gobirawa","Katsina Road"],
    "Gaya": ["Gaya Central","Gaya East","Gaya North","Gaya South","Gaya West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Wudil": ["Wudil Central","Wudil East","Wudil North","Wudil South","Wudil West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Rano": ["Rano Central","Rano East","Rano North","Rano South","Rano West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Sumaila": ["Sumaila Central","Sumaila East","Sumaila North","Sumaila South","Sumaila West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Warawa": ["Warawa Central","Warawa East","Warawa North","Warawa South","Warawa West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Bebeji": ["Bebeji Central","Bebeji East","Bebeji North","Bebeji South","Bebeji West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Ajingi": ["Ajingi Central","Ajingi East","Ajingi North","Ajingi South","Ajingi West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Albasu": ["Albasu Central","Albasu East","Albasu North","Albasu South","Albasu West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Bagwai": ["Bagwai Central","Bagwai East","Bagwai North","Bagwai South","Bagwai West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Bunkure": ["Bunkure Central","Bunkure East","Bunkure North","Bunkure South","Bunkure West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Dawakin Kudu": ["Dawakin Kudu Central","Dawakin Kudu East","Dawakin Kudu North","Dawakin Kudu South","Dawakin Kudu West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Dawakin Tofa": ["Dawakin Tofa Central","Dawakin Tofa East","Dawakin Tofa North","Dawakin Tofa South","Dawakin Tofa West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Doguwa": ["Doguwa Central","Doguwa East","Doguwa North","Doguwa South","Doguwa West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Gabasawa": ["Gabasawa Central","Gabasawa East","Gabasawa North","Gabasawa South","Gabasawa West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Garko": ["Garko Central","Garko East","Garko North","Garko South","Garko West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Garum Mallam": ["Garum Mallam Central","Garum Mallam East","Garum Mallam North","Garum Mallam South","Garum Mallam West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Gezawa": ["Gezawa Central","Gezawa East","Gezawa North","Gezawa South","Gezawa West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Gwarzo": ["Gwarzo Central","Gwarzo East","Gwarzo North","Gwarzo South","Gwarzo West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Kabo": ["Kabo Central","Kabo East","Kabo North","Kabo South","Kabo West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Karaye": ["Karaye Central","Karaye East","Karaye North","Karaye South","Karaye West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Kibiya": ["Kibiya Central","Kibiya East","Kibiya North","Kibiya South","Kibiya West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Kiru": ["Kiru Central","Kiru East","Kiru North","Kiru South","Kiru West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Kumbotso": ["Kumbotso Central","Kumbotso East","Kumbotso North","Kumbotso South","Kumbotso West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Kunchi": ["Kunchi Central","Kunchi East","Kunchi North","Kunchi South","Kunchi West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Kura": ["Kura Central","Kura East","Kura North","Kura South","Kura West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Madobi": ["Madobi Central","Madobi East","Madobi North","Madobi South","Madobi West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Makoda": ["Makoda Central","Makoda East","Makoda North","Makoda South","Makoda West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Minjibir": ["Minjibir Central","Minjibir East","Minjibir North","Minjibir South","Minjibir West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Rimin Gado": ["Rimin Gado Central","Rimin Gado East","Rimin Gado North","Rimin Gado South","Rimin Gado West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Rogo": ["Rogo Central","Rogo East","Rogo North","Rogo South","Rogo West","Gunduwawa","Kiyawa","Makama","Rogo Town","Sansani"],
    "Shanono": ["Shanono Central","Shanono East","Shanono North","Shanono South","Shanono West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Takai": ["Takai Central","Takai East","Takai North","Takai South","Takai West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Tofa": ["Tofa Central","Tofa East","Tofa North","Tofa South","Tofa West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Tsanyawa": ["Tsanyawa Central","Tsanyawa East","Tsanyawa North","Tsanyawa South","Tsanyawa West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
    "Tudun Wada": ["Tudun Wada Central","Tudun Wada East","Tudun Wada North","Tudun Wada South","Tudun Wada West","Gunduwawa","Kiyawa","Makama","Rogo","Sansani"],
  },
  "Rivers": {
    "Port Harcourt": ["Diobu","Ekolu","Mile 1","Mile 2","Mile 3","GRA Phase 1","GRA Phase 2","GRA Phase 3","Old GRA","Rumuola"],
    "Obio-Akpor": ["Elelenwo","Eneka","Mgbuoba","Mgbuodorlu","Rumueme","Rumuigbo","Rumuokoro","Rumuolumeni","Rumuosi","Trans-Amadi"],
    "Ikwerre": ["Ipo","Igwuruta","Igwuruta-Ali","Omagwa","Omoku","Rukpokwu","Rumudara","Rumuji","Rumuola","Rumurolu"],
    "Etche": ["Igbo","Mba","Okehi","Omuma","Ulakwo","Umuoye","Umunyeali","Umuoma","Umuoshi","Umuotoro"],
    "Ahoada East": ["Ahoada","Ekpeye","Igbuduya","Igburu","Mbiama","Ndoni","Odioku","Ohiamini","Okarki","Ula-Ehuda"],
    "Ahoada West": ["Ahoada West Central","Ediro","Ihugbogo","Joinkrama","Odiereke","Odioma","Ologbo","Omoku","Torugbene","Ula-Upata"],
    "Gokana": ["Baen","Bera","Gokhana","K-Dere","Kono","Mogho","Nonwa-Tai","Nyokuru","Tai","Ueken"],
    "Khana": ["Bomu","Buan","Deken","Kpean","Lueku","Nyokuru","Sogho","Sii","Ter","Ueken"],
    "Eleme": ["Agbonchia","Akpajo","Aleto","Ebubu","Ele","Eleme","Ogale","Okrika","Onne","Rumuolumeni"],
    "Bonny": ["Bonny","Finima","Iwofe","Minima","Nkpolu-Oroworukwo","Odufor","Oruigbo","Peterside","Tom Polo","Woji"],
    "Degema": ["Abissa","Bakana","Bile","Bolo","Degema","Ke","Odeama","Okochiri","Old Bakana","Usokun"],
    "Tai": ["Mogho","Nyokuru","Nonwa","Nonwa-Tai","Sogho","Sii","Ter","Ueken","Tai Central","Baa"],
    "Oyigbo": ["Afam","Isiokpo","Mgbuka","Ndele","Obite","Odufor","Ogbakiri","Omer","Oroworukwo","Oyigbo Central"],
    "Okrika": ["Ibaka","Okrika","Ogu","Bolo Inland","Abuloma","Agip","Mgbuoshimini","Nkpolu","Rumuola","Trans-Amadi"],
    "Andoni": ["Ataba","Ayama","Bare","Eeke","Ekede","Ibe-Ama","Ngo","Okoroete","Unyeada","Waakiri"],
    "Asari-Toru": ["Abonnema","Akabuka","Akuku","Buguma","Akulga","Ke","Obonoma","Offie-Ama","Otabagi","Tombia"],
    "Akuku-Toru": ["Abonnema","Angulama","Bukuma","Itigidi","Iyiama","Ke","Obonoma","Ofoin-Ama","Tombia","Usokun"],
    "Abua/Odual": ["Abua East","Abua North","Abua South","Abua West","Odual North","Odual South","Abua Central","Orashi","Obrikama","Otabagi"],
    "Ogba/Egbema/Ndoni": ["Egbema","Ndoni","Ogba","Omoku","Usomini","Odiagi","Orashi","Ula-Ehuda","Mbiama","Ndele"],
    "Opobo/Nkoro": ["Andoni","Nkoro","Opobo","Andoni South","Opobo Central","Nkoro Central","Opobo West","Andoni North","Nkoro South","Opobo East"],
    "Ogu/Bolo": ["Ogu","Bolo","Ogu Central","Bolo Central","Bolo North","Ogu North","Bolo South","Ogu South","Ogu West","Bolo West"],
    "Omuma": ["Omuma Central","Omuma East","Omuma North","Omuma South","Omuma West","Igbo","Mba","Ulakwo","Umuoye","Umunyeali"],
    "Emohua": ["Emohua Central","Emohua East","Emohua North","Emohua South","Emohua West","Rumuji","Rumurolu","Rumuola","Rumuosi","Trans-Amadi"],
  },
  "FCT": {
    "Municipal Area Council": ["Cadastral Zone","Central Area","Garki","Gudu","Gwarinpa","Jabi","Jahi","Kado","Maitama","Wuse"],
    "Abaji": ["Abaji","Agyana","Eggan","Gawu","Gudako","Nuku","Yaba","Rimba","Abaji Central","Bassa"],
    "Bwari": ["Bwari","Dutse Alhaji","Garki","Gbaupe","Igu","Kogo","Kubwa","Ushafa","Usuma","Zuba"],
    "Gwagwalada": ["Gwagwalada Central","Dobi","Giri","Gwako","Ibwa","Ikwa","Kutunku","Paikon-Kore","Zuba","Quarters"],
    "Kuje": ["Kuje","Chibiri","Gaube","Gwargwada","Kilankwa","Kuje Central","Rubochi","Sheda","Toge","Wan"],
    "Kwali": ["Kwali","Dafa","Gawu","Gboroke","Pai","Yangoji","Yebu","Zuba","Kwali Central","Wako"],
  },
  "Oyo": {
    "Ibadan North": ["Agodi","Bashorun","Bodija","Challenge","Idi-Ape","Ido","Iwo Road","Lagelu","Mapo","Oranyan"],
    "Ibadan North-East": ["Akinyele","Awotan","Elebu","Gbagi","Iwo Road","Monatan","Ojoo","Sango","Shasha","Omi-Adio"],
    "Ibadan North-West": ["Agodi","Dugbe","Oke-Badan","Oke-Padre","Onireke","Ring Road","Sango","Secretariat","Yemetu","Iyaganku"],
    "Ibadan South-East": ["Aba","Adie-Owe","Agbeni","Inalende","Isale-Ijebu","Oje","Olomi","Opele","Oranyan","Yemetu"],
    "Ibadan South-West": ["Agodi","Alaafin","Beere","Gbagi","Iyaganku","Mapo","Molete","Oke-Ado","Olopomewa","Ring Road"],
    "Ogbomosho North": ["Arowomole","Agunbelewo","Ekinrin-Adde","Ido-Aro","Isale-Afon","Masifa","Ogbomosho Central","Okelerin","Owode","Takie"],
    "Ogbomosho South": ["Arowomole","Agunbelewo","Isale-Afon","Masifa","Ogbomosho South Central","Okelerin","Owode","Takie","Oke-Ado","Saabo"],
    "Oyo East": ["Atiba","Ayede","Igbo-Ora","Ilora","Kisi","Lalupon","Malete","Oyo","Saki","Tede"],
    "Oyo West": ["Atiba","Ayede","Igbo-Ora","Ilora","Kisi","Lalupon","Malete","Oyo","Saki","Tede"],
    "Akinyele": ["Akinyele Central","Awotan","Elebu","Gbagi","Iwo Road","Monatan","Ojoo","Sango","Shasha","Omi-Adio"],
    "Atiba": ["Atiba Central","Oyo East","Oyo West","Saki East","Saki West","Ogbomosho North","Ogbomosho South","Ogo Oluwa","Olorunsogo","Oluyole"],
    "Atisbo": ["Atisbo Central","Atisbo East","Atisbo North","Atisbo South","Atisbo West","Ago-Are","Tede","Okeho","Igboho","Saki"],
    "Egbeda": ["Egbeda Central","Egbeda East","Egbeda North","Egbeda South","Egbeda West","Awotan","Elebu","Gbagi","Iwo Road","Monatan"],
    "Ibarapa Central": ["Igbo-Ora Central","Ibarapa Central East","Ibarapa Central North","Ibarapa Central South","Ibarapa Central West","Idere","Tapa","Aiyete","Eruwa","Lanlate"],
    "Ibarapa East": ["Eruwa","Ibarapa East Central","Ibarapa East North","Ibarapa East South","Ibarapa East West","Idere","Tapa","Aiyete","Igbo-Ora","Lanlate"],
    "Ibarapa North": ["Aiyete","Ibarapa North Central","Ibarapa North East","Ibarapa North South","Ibarapa North West","Idere","Tapa","Igbo-Ora","Eruwa","Lanlate"],
    "Ido": ["Ido Central","Ido East","Ido North","Ido South","Ido West","Omi-Adio","Apete","Alakia","Olorunda","Iyana Church"],
    "Irepo": ["Kisi","Irepo Central","Irepo East","Irepo North","Irepo South","Irepo West","Ago-Are","Tede","Okeho","Igboho"],
    "Iseyin": ["Iseyin Central","Iseyin East","Iseyin North","Iseyin South","Iseyin West","Ago-Are","Tede","Okeho","Igboho","Saki"],
    "Itesiwaju": ["Itesiwaju Central","Itesiwaju East","Itesiwaju North","Itesiwaju South","Itesiwaju West","Ago-Are","Tede","Okeho","Igboho","Saki"],
    "Iwajowa": ["Iwajowa Central","Iwajowa East","Iwajowa North","Iwajowa South","Iwajowa West","Ago-Are","Tede","Okeho","Igboho","Saki"],
    "Kajola": ["Kajola Central","Kajola East","Kajola North","Kajola South","Kajola West","Ago-Are","Tede","Okeho","Igboho","Saki"],
    "Lagelu": ["Lagelu Central","Lagelu East","Lagelu North","Lagelu South","Lagelu West","Awotan","Elebu","Gbagi","Iwo Road","Monatan"],
    "Ogo Oluwa": ["Ogo Oluwa Central","Ogo Oluwa East","Ogo Oluwa North","Ogo Oluwa South","Ogo Oluwa West","Ogbomosho North","Ogbomosho South","Olorunsogo","Oluyole","Ona Ara"],
    "Olorunsogo": ["Olorunsogo Central","Olorunsogo East","Olorunsogo North","Olorunsogo South","Olorunsogo West","Ogbomosho North","Ogbomosho South","Ogo Oluwa","Oluyole","Ona Ara"],
    "Oluyole": ["Oluyole Central","Oluyole East","Oluyole North","Oluyole South","Oluyole West","Egbeda","Ido","Ibarapa Central","Ibarapa East","Ibarapa North"],
    "Ona Ara": ["Ona Ara Central","Ona Ara East","Ona Ara North","Ona Ara South","Ona Ara West","Egbeda","Ido","Ibarapa Central","Ibarapa East","Ibarapa North"],
    "Orelope": ["Orelope Central","Orelope East","Orelope North","Orelope South","Orelope West","Ago-Are","Tede","Okeho","Igboho","Saki"],
    "Ori Ire": ["Ori Ire Central","Ori Ire East","Ori Ire North","Ori Ire South","Ori Ire West","Ogbomosho North","Ogbomosho South","Ogo Oluwa","Olorunsogo","Oluyole"],
    "Saki East": ["Saki East Central","Saki East East","Saki East North","Saki East South","Saki East West","Ago-Are","Tede","Okeho","Igboho","Saki"],
    "Saki West": ["Saki West Central","Saki West East","Saki West North","Saki West South","Saki West West","Ago-Are","Tede","Okeho","Igboho","Saki"],
    "Surulere": ["Surulere Central","Surulere East","Surulere North","Surulere South","Surulere West","Ogbomosho North","Ogbomosho South","Ogo Oluwa","Olorunsogo","Oluyole"],
    "Afijio": ["Afijio Central","Afijio East","Afijio North","Afijio South","Afijio West","Oyo East","Oyo West","Atiba","Atisbo","Egbeda"],
  },
};

// Generate default wards for LGAs not explicitly listed
function defaultWards(lga) {
  return [
    `${lga} Ward 1`, `${lga} Ward 2`, `${lga} Ward 3`, `${lga} Ward 4`,
    `${lga} Ward 5`, `${lga} Ward 6`, `${lga} Ward 7`, `${lga} Ward 8`,
    `${lga} Ward 9`, `${lga} Ward 10`,
  ];
}

export function getLGAs(state) {
  return LGAS[state] || [];
}

export function getWards(state, lga) {
  if (!state || !lga) return [];
  const stateWards = WARDS[state];
  if (stateWards && stateWards[lga]) return stateWards[lga];
  return defaultWards(lga);
}
