const fmtN = (n) =>
  `N${Number(n || 0).toLocaleString("en-NG", { minimumFractionDigits: 2 })}`;

function buildHeader(doc, title, subtitle, color) {
  const W = doc.internal.pageSize.getWidth();
  doc.setFillColor(...color);
  doc.rect(0, 0, W, 30, "F");

  // Brand name
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("KudiAI Track", W / 2, 9, { align: "center" });

  // Business name
  doc.setFontSize(14);
  doc.text(title, W / 2, 19, { align: "center" });

  // Subtitle badge
  doc.setFillColor(0, 0, 0, 40);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(subtitle, W / 2, 27, { align: "center" });
}

function buildFooter(doc, y) {
  const W = doc.internal.pageSize.getWidth();
  doc.setFillColor(248, 250, 252);
  doc.rect(0, y, W, 14, "F");
  doc.setFontSize(7);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(150);
  doc.text(
    `Generated by KudiAI Track  |  ${new Date().toLocaleString("en-NG")}`,
    W / 2, y + 9,
    { align: "center" }
  );
}

function drawRow(doc, y, label, value, highlight = false) {
  const W = doc.internal.pageSize.getWidth();
  if (highlight) {
    doc.setFillColor(240, 253, 244);
    doc.rect(8, y - 4, W - 16, 9, "F");
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(100);
  doc.text(label, 12, y);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(highlight ? [22, 101, 52] : 40);
  doc.text(String(value || "—"), W - 12, y, { align: "right", maxWidth: W - 65 });
  return y + 9;
}

function drawDivider(doc, y) {
  const W = doc.internal.pageSize.getWidth();
  doc.setDrawColor(226, 232, 240);
  doc.line(10, y, W - 10, y);
  return y + 4;
}

/* ── Transaction Receipt ──────────────────────────────────────────── */
export async function exportTransactionReceipt(transaction, profile) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a6" });
  const W = doc.internal.pageSize.getWidth();
  const isIn = transaction.type === "in";
  const green = [5, 150, 105];

  buildHeader(doc, profile.business_name || "My Business", "TRANSACTION RECEIPT", green);

  // Amount hero
  const amtColor = isIn ? [22, 163, 74] : [220, 38, 38];
  doc.setFillColor(...(isIn ? [240, 253, 244] : [254, 242, 242]));
  doc.rect(8, 33, W - 16, 22, "F");
  doc.setTextColor(...amtColor);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text(isIn ? "CASH IN" : "CASH OUT", W / 2, 40, { align: "center" });
  doc.setFontSize(18);
  doc.text(fmtN(transaction.amount), W / 2, 51, { align: "center" });

  let y = 62;
  y = drawDivider(doc, y);

  const rows = [
    ["Item",      transaction.item_name],
    ["Date",      transaction.transaction_date],
    ["Category",  transaction.category],
    ...(transaction.quantity > 1 ? [["Quantity", transaction.quantity]] : []),
    ["Payment",   transaction.payment_type],
    ...(transaction.customer_name ? [["Customer", transaction.customer_name]] : []),
    ...(transaction.note ? [["Note", transaction.note]] : []),
  ];
  rows.forEach(([label, value]) => {
    y = drawRow(doc, y, label, value);
  });

  y = drawDivider(doc, y + 2);
  y = drawRow(doc, y + 1, "Total", fmtN(transaction.amount), true);

  buildFooter(doc, y + 8);
  doc.save(`receipt_${transaction.id || Date.now()}.pdf`);
}

/* ── Credit Statement ─────────────────────────────────────────────── */
export async function exportCreditStatement(credit, profile) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a5" });
  const W = doc.internal.pageSize.getWidth();
  const amber = [245, 158, 11];

  buildHeader(doc, profile.business_name || "My Business", "CREDIT STATEMENT", amber);

  // Customer hero
  doc.setFillColor(255, 251, 235);
  doc.rect(8, 33, W - 16, 22, "F");
  doc.setTextColor(180, 83, 9);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(credit.customer_name, W / 2, 42, { align: "center" });
  doc.setFontSize(8);
  doc.text("OUTSTANDING: " + fmtN(credit.outstanding), W / 2, 51, { align: "center" });

  let y = 62;
  y = drawDivider(doc, y);

  const rows = [
    ["Phone",       credit.phone],
    ["Address",     credit.address],
    ["Total Owed",  fmtN(credit.total_amount)],
    ["Amount Paid", fmtN(credit.amount_paid)],
    ["Outstanding", fmtN(credit.outstanding)],
    ["Date Given",  credit.date_given],
    ["Due Date",    credit.due_date],
    ["Status",      (credit.status || "").toUpperCase()],
    ...(credit.notes ? [["Notes", credit.notes]] : []),
  ];
  rows.forEach(([label, value]) => {
    y = drawRow(doc, y, label, value, label === "Outstanding");
  });

  buildFooter(doc, y + 8);
  doc.save(`credit_${(credit.customer_name || "statement").replace(/\s+/g, "_")}.pdf`);
}

/* ── Aso Savings Statement ────────────────────────────────────────── */
export async function exportAsoStatement(client, profile) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a5" });
  const W = doc.internal.pageSize.getWidth();
  const violet = [124, 58, 237];

  buildHeader(doc, profile.business_name || "My Business", "ASO SAVINGS STATEMENT", violet);

  // Client hero
  doc.setFillColor(245, 243, 255);
  doc.rect(8, 33, W - 16, 22, "F");
  doc.setTextColor(91, 33, 182);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(client.full_name, W / 2, 42, { align: "center" });
  doc.setFontSize(8);
  doc.text("BALANCE: " + fmtN(client.current_balance), W / 2, 51, { align: "center" });

  let y = 62;
  y = drawDivider(doc, y);

  const rows = [
    ["Phone",            client.phone],
    ["State / LGA",      `${client.state || ""} / ${client.lga || ""}`],
    ["Frequency",        client.contribution_frequency],
    ["Contribution",     fmtN(client.contribution_amount)],
    ["Total Saved",      fmtN(client.total_saved)],
    ["Total Withdrawn",  fmtN(client.total_withdrawn)],
    ["Current Balance",  fmtN(client.current_balance)],
    ["Next Due",         client.next_contribution_date],
    ["Registered",       client.registration_date],
  ];
  rows.forEach(([label, value]) => {
    y = drawRow(doc, y, label, value, label === "Current Balance");
  });

  buildFooter(doc, y + 8);
  doc.save(`aso_${(client.full_name || "statement").replace(/\s+/g, "_")}.pdf`);
}
