// Receipt PDF — A4 portrait, real vector text (selectable, searchable, copyable).
//
// This replaces the old "screenshot of the on-screen card wrapped in a PDF": every
// character here is text in the file, so a reference or amount can be copied out
// of it. Pure layout — no fetching, no browser APIs — so it can be tested in Node
// (see generateReceiptPdf.js for the browser wrapper that loads fonts and the logo).
//
// Everything printed comes from the receipt spec built by receiptConfig.js:
// the stored reference, the stored server timestamp (rendered in WAT), the method,
// the running balance, the business's own contact details and the amount in words.

import { amountToWords } from "./amountInWords";
import { formatWATDate, formatWATTime } from "./wat";

const NAVY  = [15, 28, 69];
const GREEN = [61, 168, 41];
const AMBER = [217, 119, 6];
const RED   = [220, 38, 38];
const INK   = [30, 41, 59];
const MUTED = [100, 116, 139];
const HAIR  = [226, 232, 240];
const PANEL = [248, 250, 252];

const PAGE_W = 210;
const ML = 18;
const MR = 18;
const RIGHT = PAGE_W - MR;
const CW = PAGE_W - ML - MR;
const CONTENT_BOTTOM = 266;          // rows must stop above the footer

const STATUS = {
  success:    { label: "SUCCESSFUL", fg: [15, 123, 62],  bg: [220, 252, 231] },
  pending:    { label: "PENDING",    fg: [146, 64, 14],  bg: [254, 243, 199] },
  processing: { label: "PENDING",    fg: [146, 64, 14],  bg: [254, 243, 199] },
  failed:     { label: "FAILED",     fg: [153, 27, 27],  bg: [254, 226, 226] },
  reversed:   { label: "REVERSED",   fg: [55, 65, 81],   bg: [243, 244, 246] },
};

// Row labels the layout prints itself (or that the status pill already says) —
// the builder's copy of them is dropped so nothing appears twice.
const OWN_ROWS = new Set(["reference", "payment method", "status", "balance after", "account balance after", "remaining balance", "outstanding", "current balance", "pins issued"]);

export function fmtNaira(n) {
  const [int, dec] = Number(n || 0).toFixed(2).split(".");
  return "₦" + int.replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "." + dec;
}

/**
 * Draw the receipt onto a jsPDF document.
 * @param doc    a fresh jsPDF instance (A4, mm)
 * @param data   receipt spec from receiptConfig.js
 * @param assets { logo?: dataURL, font: "NotoSans" | "helvetica" }
 */
export function renderReceiptPdf(doc, data, { logo = null, providerLogo = null, font = "helvetica" } = {}) {
  const custom = font !== "helvetica";
  // helvetica has no naira sign — spell it out rather than print a broken glyph
  const t = (s) => (custom ? String(s ?? "") : String(s ?? "").replace(/₦/g, "NGN "));
  const setReg  = (size, color = INK) => { doc.setFont(font, "normal"); doc.setFontSize(size); doc.setTextColor(...color); };
  const setBold = (size, color = INK) => { doc.setFont(font, "bold");   doc.setFontSize(size); doc.setTextColor(...color); };
  const setMono = (size, color = INK) => { doc.setFont("courier", "bold"); doc.setFontSize(size); doc.setTextColor(...color); };

  const isStatement = data.kind === "statement";
  const status = STATUS[data.status] || STATUS.pending;
  const accent = data.status === "failed" ? RED
               : data.status === "pending" || data.status === "processing" ? AMBER
               : data.direction === "in" ? GREEN : AMBER;
  const hasClock = !!data.occurredAt;
  const stamp = hasClock ? `${formatWATDate(data.occurredAt)}, ${formatWATTime(data.occurredAt)}` : (data.datetime || "");

  // ── Page furniture (every page) ────────────────────────────────────────────
  const drawFooter = () => {
    doc.setDrawColor(...HAIR); doc.setLineWidth(0.3);
    doc.line(ML, 277, RIGHT, 277);
    setReg(7.5, MUTED);
    doc.text("Generated by KudiAI Track · A product of Amaya & Co. Technologies", PAGE_W / 2, 282, { align: "center" });
    doc.text("This receipt is computer generated and valid without signature.", PAGE_W / 2, 286, { align: "center" });
  };

  // ── Header ─────────────────────────────────────────────────────────────────
  if (logo) {
    try { doc.addImage(logo, "PNG", ML, 12, 12, 12); } catch (_) { /* logo is decoration only */ }
  }
  setBold(14, NAVY);
  doc.text("KudiAI Track", logo ? ML + 15 : ML, 18.5);
  setReg(8, MUTED);
  doc.text("Amaya & Co.", logo ? ML + 15 : ML, 23);

  setBold(9, INK);
  doc.text(isStatement ? "STATEMENT" : "TRANSACTION RECEIPT", RIGHT, 17.5, { align: "right" });
  setReg(8, MUTED);
  doc.text("KudiAI Track · Amaya & Co.", RIGHT, 23, { align: "right" });

  doc.setFillColor(...accent);
  doc.rect(0, 30, PAGE_W, 1.4, "F");

  // ── Title + timestamp ──────────────────────────────────────────────────────
  let y = 44;
  setBold(16, INK);
  doc.text(t(data.title || "Receipt"), ML, y);
  setReg(9.5, MUTED);
  y += 6;
  if (stamp) doc.text(stamp, ML, y);

  // Provider logo (electricity DISCO) on the right of the title row, scaled to fit a 38 x 16 mm box
  if (providerLogo && providerLogo.w > 0 && providerLogo.h > 0) {
    const k = Math.min(38 / providerLogo.w, 16 / providerLogo.h);
    try { doc.addImage(providerLogo.dataUrl, "PNG", RIGHT - providerLogo.w * k, 34.5, providerLogo.w * k, providerLogo.h * k); }
    catch (_) { /* the logo is decoration only */ }
  }

  // ── Amount box: amount left, status right, amount in words underneath ─────
  y += 8;
  const boxH = 36;
  doc.setFillColor(...PANEL); doc.setDrawColor(...HAIR); doc.setLineWidth(0.3);
  doc.roundedRect(ML, y, CW, boxH, 3, 3, "FD");

  setBold(7.5, MUTED);
  doc.text(isStatement ? (data.balanceLabel || "BALANCE").toUpperCase() : "AMOUNT", ML + 7, y + 9);

  const amountText = t(fmtNaira(data.amount));
  const pillText = status.label;
  setBold(8, status.fg);
  const pillW = doc.getTextWidth(pillText) + 10;
  let fs = 28;
  setBold(fs, INK);
  while (doc.getTextWidth(amountText) > CW - 14 - pillW - 4 && fs > 14) { fs -= 1; setBold(fs, INK); }
  doc.text(amountText, ML + 7, y + 22);

  doc.setFillColor(...status.bg);
  doc.roundedRect(RIGHT - 7 - pillW, y + 14.5, pillW, 8, 4, 4, "F");
  setBold(8, status.fg);
  doc.text(pillText, RIGHT - 7 - pillW / 2, y + 19.8, { align: "center" });

  const words = amountToWords(data.amount);
  if (words) {
    setReg(7.5, MUTED);
    doc.text(words, ML + 7, y + 30, { maxWidth: CW - 14 });
  }
  y += boxH + 8;

  // ── Detail rows ────────────────────────────────────────────────────────────
  const rows = [];
  if (data.hasRef && data.receiptRef) rows.push({ label: "Reference", value: data.receiptRef, mono: true });
  else if (!isStatement && data.receiptRef) rows.push({ label: "Reference", value: data.receiptRef, muted: true });
  if (hasClock) {
    rows.push({ label: "Date", value: formatWATDate(data.occurredAt) });
    rows.push({ label: "Time", value: formatWATTime(data.occurredAt) });
  } else if (data.datetime) {
    rows.push({ label: "Date", value: data.datetime });
  }
  if (data.method) rows.push({ label: "Payment Method", value: data.method });

  for (const f of data.fields || []) {
    if (!f || f.retrievable || f.value == null || f.value === "") continue;
    const key = String(f.label || "").trim().toLowerCase();
    if (OWN_ROWS.has(key)) continue;
    rows.push({ label: String(f.label || "").trim(), value: String(f.value), indent: /^\s/.test(String(f.label || "")) });
  }

  if (data.balanceAfter != null && !isStatement) {
    rows.push({ label: data.balanceLabel || "Balance After", value: fmtNaira(data.balanceAfter), strong: true });
  }
  if (data.recordedBy) rows.push({ label: "Recorded by", value: data.recordedBy });
  const bizRows = [];
  if (data.businessName)    bizRows.push({ label: "Business", value: data.businessName });
  if (data.businessAddress) bizRows.push({ label: "Address",  value: data.businessAddress });
  if (data.businessPhone)   bizRows.push({ label: "Phone",    value: data.businessPhone });
  // the recorded-by row was already pushed above; avoid a duplicate if a builder also listed it
  const seen = new Set();
  const all = [...rows, ...bizRows].filter((r) => { const k = r.label.toLowerCase() + "|" + r.value; if (seen.has(k)) return false; seen.add(k); return true; });

  const LABEL_W = 44;
  const VALUE_W = CW - LABEL_W - 6;
  let page = 1;
  const newPage = () => { drawFooter(); doc.addPage(); page += 1; y = 24; };

  all.forEach((row, idx) => {
    const lines = String(row.value).split("\n").flatMap((ln, i) => {
      if (row.mono || row.strong) return [{ text: ln, first: i === 0 }];
      if (i === 0) setBold(9.5); else setReg(8.5);
      return doc.splitTextToSize(t(ln), VALUE_W).map((p, k) => ({ text: p, first: i === 0 && k === 0 }));
    });
    const h = lines.length * 4.6 + 4.2;
    if (y + h > CONTENT_BOTTOM) newPage();

    setReg(9, MUTED);
    doc.text(t(row.label), ML + (row.indent ? 4 : 0), y + 4.2);

    let ly = y + 4.2;
    for (const ln of lines) {
      if (row.mono)        setMono(10.5, INK);
      else if (row.strong) setBold(11, INK);
      else if (row.muted)  setReg(9.5, MUTED);
      else                 { setReg(ln.first ? 9.5 : 8.5, ln.first ? INK : MUTED); if (ln.first) doc.setFont(font, "bold"); }
      doc.text(row.mono ? ln.text : t(ln.text), RIGHT, ly, { align: "right" });
      ly += 4.6;
    }
    y += h;
    if (idx < all.length - 1) { doc.setDrawColor(...HAIR); doc.setLineWidth(0.2); doc.line(ML, y - 0.6, RIGHT, y - 0.6); }
  });

  // ── Verify block ───────────────────────────────────────────────────────────
  if (data.hasRef && data.receiptRef) {
    y += 6;
    if (y + 16 > 274) newPage();   // the block ends above the footer rule at 277
    doc.setFillColor(...PANEL); doc.setDrawColor(...HAIR); doc.setLineWidth(0.3);
    doc.roundedRect(ML, y, CW, 16, 2.5, 2.5, "FD");
    // vector padlock (the built-in fonts have no lock glyph)
    const lx = ML + 6, ly = y + 5;
    doc.setDrawColor(...GREEN); doc.setLineWidth(0.5);
    doc.circle(lx + 2.2, ly + 1.4, 1.3, "S");
    doc.setFillColor(...GREEN);
    doc.roundedRect(lx, ly + 2, 4.4, 3.6, 0.7, 0.7, "F");
    setBold(9.5, INK);
    doc.text("Verify at ", ML + 14, y + 7);
    const vx = ML + 14 + doc.getTextWidth("Verify at ");
    setBold(9.5, GREEN);
    doc.textWithLink("kudiai.app/verify", vx, y + 7, { url: `https://kudiai.app/verify?ref=${encodeURIComponent(data.receiptRef)}` });
    setReg(8.5, MUTED);
    doc.text("Reference: ", ML + 14, y + 12.2);
    const rx = ML + 14 + doc.getTextWidth("Reference: ");
    setMono(9, INK);
    doc.text(data.receiptRef, rx, y + 12.2);
  }

  drawFooter();
  return { pages: page };
}
