// Builds standardized receipt data from raw transaction records per screen type.
// Every function returns a common shape consumed by TransactionDetailModal + ReceiptCard.

import { ledgerTypeLabel } from './helpers';
import { formatWAT, formatWATDate, watStamp } from './wat';
import { discoFromRecord, DISCO_LABELS } from './electricityLogos';
import { describeBank } from './bankLogos';
import { billBrandFromRecord } from './billLogos';
import { BILL_CATEGORIES } from './historyEntries';

// Which processor actually moved the money. Never assume one: a receipt that
// names the wrong processor is worse than one that names none.
const PROCESSORS = {
  wallet:      { label: 'KudiAI Wallet',   line: 'Paid from your KudiAI Wallet' },
  paystack:    { label: 'Paystack',        line: 'Payment securely processed via Paystack' },
  flutterwave: { label: 'Flutterwave',     line: 'Payment securely processed via Flutterwave' },
  cashback:    { label: 'KudiAI cashback', line: 'Paid with KudiAI cashback' },
  cash:        { label: 'Cash',            line: 'Paid in cash' },
};

/** 'wallet' | 'paystack' | … -> { label, line }, or null when the funding source is not recorded. */
export function processorFor(via) {
  return PROCESSORS[String(via || '').toLowerCase()] || null;
}

// The timestamp on every receipt is the stored server time, in WAT, with seconds.
// A date-only value (a row still in the offline queue has no server timestamp yet)
// carries no clock time, so only the date is shown — never an invented time.
export function formatReceiptDateTime(dt) {
  if (!dt) return '—';
  if (/^\d{4}-\d{2}-\d{2}$/.test(String(dt))) return formatWATDate(dt);
  return formatWAT(dt);
}

// A receipt's reference is generated by the database when the row is created and
// stored on it (receipt_ref, KDT-YYYYMM-XXXXXXXX). It is never derived on the device.
// A row that has not reached the server yet has none, and the receipt says so.
export const REF_PENDING = 'Assigned on sync';

// Filenames are `<title>_<ref>_<YYYYMMDD-HHMM>.<ext>` (WAT), e.g.
//   airtime-top-up_KDT-202609-X7K2M9PQ_20260918-2114.pdf
export function receiptFilenames(id, createdAt, title, storedRef) {
  const slug = String(title || 'receipt')
    .toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 28) || 'receipt';
  const cleanRef = String(storedRef || '').replace(/[^A-Za-z0-9-]/g, '');
  const idPart = cleanRef || String(id || '').replace(/[^A-Za-z0-9]/g, '').slice(0, 8).toUpperCase() || 'pending';
  const base = `${slug}_${idPart}_${watStamp(createdAt) || 'undated'}`;
  return { ref: cleanRef || REF_PENDING, hasRef: !!cleanRef, image: `${base}.png`, pdf: `${base}.pdf` };
}

const numOrNull = (v) => (v === null || v === undefined || v === '' || !Number.isFinite(Number(v)) ? null : Number(v));

// The business's own contact details, from a profile row (owner/staff/manager portals).
export function bizFromProfile(profile) {
  return {
    address: profile?.business_address || profile?.address || '',
    phone:   profile?.business_phone   || profile?.phone   || '',
  };
}

// The extra facts the PDF prints, common to every receipt: the stored server
// timestamp, how it was paid, the balance after this entry, and the business's
// contact details when the caller has them. Absent facts stay null and are left
// off the PDF rather than shown as a dash.
function meta(row, { hasRef, method, balanceAfter, balanceLabel, biz } = {}) {
  return {
    hasRef:          !!hasRef,
    occurredAt:      row?.created_at || null,
    method:          method || null,
    balanceAfter:    numOrNull(balanceAfter),
    balanceLabel:    balanceLabel || 'Balance After',
    businessAddress: biz?.address || null,
    businessPhone:   biz?.phone || null,
  };
}

// Locale-independent: always produces ₦15,000.00 regardless of WebView locale.
function fmtAmt(n) {
  const [int, dec] = Number(n || 0).toFixed(2).split('.');
  return '₦' + int.replace(/\B(?=(\d{3})+(?!\d))/g, ',') + '.' + dec;
}

function humanize(s) {
  if (!s) return '—';
  return String(s).replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

// ── Standard transaction (income/expense from Transactions screen) ─────────────
// How a cash-book row was paid. A bill row's payment_type is just "bill_payment"
// (the category, not a method), so its method comes from the recorded funding
// source; a legacy bill row that never recorded one shows no method at all.
function transactionMethod(txn) {
  if (txn.payment_type === 'bill_payment') return billPaidVia(txn) ? processorFor(billPaidVia(txn)).label : null;
  return txn.payment_type ? humanize(txn.payment_type) : null;
}

// The funding source of a bill: recorded in bill_details at payment time; older
// wallet-paid rows are recognisable from their note. Anything else is unknown —
// never guessed.
function billPaidVia(bill) {
  const recorded = bill.paidVia || bill.bill_details?.paid_via;
  if (processorFor(recorded)) return String(recorded).toLowerCase();
  if (/paid from wallet/i.test(bill.note || '')) return 'wallet';
  return null;
}

// The structured facts of a stored bill (a transactions row): the note carries them as "Key: value | Key: value" (and the printed pins after
// "__PINS__"), bill_details is the authoritative source when present. Shared by the Bills page and the general history so the same bill
// makes the same receipt wherever it is opened.
export function parseBillRecord(bill) {
  const raw = bill.note || '';
  const pinsIdx = raw.indexOf('__PINS__');
  const n = pinsIdx !== -1 ? raw.slice(0, pinsIdx) : raw;
  const pick = (rx) => n.match(rx)?.[1]?.trim() || '';

  let pinsArr;
  if (pinsIdx !== -1) {
    try { pinsArr = JSON.parse(raw.slice(pinsIdx + 8)); } catch (_) { /* a damaged pin list is left off */ }
  }
  const bd = bill.bill_details || {};

  return {
    paidVia:       bd.paid_via || undefined,
    apiRef:        bd.orderId || pick(/Ref:\s*([^\s|]+)/i),
    token:         bd.token || (() => { const t = (pick(/Token:\s*([^|]+)/i) || '').trim(); return t && !t.toLowerCase().startsWith('loading') ? t : undefined; })(),
    units:         bd.units || (pick(/Units:\s*([^|]+)/i) || '').trim() || undefined,
    network:       pick(/Network:\s*([^|]+)/i),
    phone:         pick(/Phone:\s*([^|]+)/i) || pick(/Beneficiary:\s*([^|]+)/i),
    planName:      pick(/Plan:\s*([^|]+)/i),
    smartcard:     pick(/Smartcard:\s*([^|]+)/i),
    meterNo:       pick(/Meter:\s*([^|]+)/i),
    meterAddress:  pick(/Meter Address:\s*([^|]+)/i),
    meterTypeName: pick(/Type:\s*([^|]+)/i),
    providerName:  pick(/Provider:\s*([^|]+)/i),
    platformName:  pick(/Platform:\s*([^|]+)/i),
    packageName:   pick(/Package:\s*([^|]+)/i),
    customerId:    pick(/Customer:\s*([^|]+)/i),
    accountNo:     pick(/Account:\s*([^|]+)/i),
    value:         pick(/Value:\s*([^|]+)/i),
    pinsArr:       bd.pins || pinsArr,
    cardDetails:   bd.cardDetails || undefined,
  };
}

export function buildTransactionReceipt(txn, profile) {
  // A bill opened from the general history is the same receipt as on the Bills page: its provider's logo, the smartcard / meter / token
  // details — not the plain income / expense layout below.
  if (txn.payment_type === 'bill_payment' || (BILL_CATEGORIES.has(txn.category) && txn.type !== 'in')) {
    const biz = bizFromProfile(profile);
    const r = buildBillReceipt({
      ...txn,
      ...parseBillRecord(txn),
      businessName:    profile?.business_name || 'My Business',
      businessAddress: biz.address,
      businessPhone:   biz.phone,
      staffName:       txn.staff_name || undefined,
    });
    return txn._pending ? { ...r, status: 'pending' } : r;
  }
  const isIn   = txn.type === 'in';
  const status =
    txn._pending         ? 'pending' :
    txn.bill_status === 'failed' ? 'failed' : 'success';
  const method = transactionMethod(txn);

  const isMulti = Array.isArray(txn.line_items) && txn.line_items.length > 1;
  const liFields = isMulti
    ? txn.line_items.map(li => ({
        label: li.name ? `${li.name}${(li.qty || 1) > 1 ? ` ×${li.qty}` : ''}` : '—',
        value: fmtAmt(li.lineTotal),
      }))
    : [];
  const title = isMulti
    ? `${txn.line_items.length} items`
    : txn.item_name || humanize(txn.category) || (isIn ? 'Payment Received' : 'Payment Made');
  const { ref, hasRef, image, pdf } = receiptFilenames(txn.id, txn.created_at || txn.transaction_date, title, txn.receipt_ref);
  const balanceAfter = numOrNull(txn.balance_after);
  // A bill paid through the app is booked as an expense row; its receipt follows the same rule as a bill receipt
  const isBillPayment = txn.payment_type === 'bill_payment';

  return {
    title,
    direction:   isIn ? 'in' : 'out',
    status,
    amount:      txn.amount,
    datetime:    formatReceiptDateTime(txn.created_at || txn.transaction_date),
    fields: [
      ...liFields,
      { label: 'Transaction Type', value: isIn ? 'Income' : 'Expense' },
      txn.customer_name && { label: isIn ? 'From'  : 'To',     value: txn.customer_name },
      !isMulti && txn.item_name && { label: 'Description',      value: txn.item_name },
      txn.category      && { label: 'Category',                 value: humanize(txn.category) },
      method            && { label: 'Payment Method',           value: method },
      !isMulti && txn.quantity > 1 && { label: 'Quantity',      value: String(txn.quantity) },
      txn.note          && { label: 'Note',                     value: txn.note },
      txn.staff_name    && { label: 'Recorded by',              value: txn.staff_name },
      balanceAfter != null && { label: 'Balance After',        value: fmtAmt(balanceAfter), private: isBillPayment },
                           { label: 'Reference',                value: ref, copy: hasRef },
    ].filter(Boolean),
    businessName:  profile?.business_name || 'My Business',
    issuedBy:      profile?.business_name || 'My Business',
    fees:          0,
    receiptRef:    ref,
    filenames:     { image, pdf },
    processorName: null,
    iconType:      isIn ? 'income' : 'expense',
    recordedBy:    txn.staff_name || null,
    ...meta(txn, { hasRef, method, balanceAfter, biz: bizFromProfile(profile) }),
    hideBalanceOnShare: isBillPayment,
  };
}

// ── Ajo/Aso contribution or withdrawal (from Aso screen) ─────────────────────
function buildDestinationLabel(contribution) {
  const ctx  = contribution.contribution_context || 'personal_savings';
  const type = contribution.type || '';
  // group_name: flat field some callers pass directly; ajo_groups?.name: the
  // shape a Supabase embedded select (`ajo_groups(name)`) actually returns.
  const grp  = contribution.group_name || contribution.ajo_groups?.name || '';
  const cyc  = contribution.cycle_label || '';
  const rnd  = contribution.round_number ? ` (Round ${contribution.round_number})` : '';

  if (type === 'registration_fee')  return `Registration fee — one-time`;
  if (type === 'commission')         return `Collector's fee — Day 1${cyc ? ` of ${cyc}` : ''}`;
  if (type === 'withdrawal_fee')     return `Withdrawal fee${cyc ? ` — ${contribution.fee_percent ? contribution.fee_percent + '% of ' : ''}${cyc}` : ''}`;
  if ((type === 'disbursement' || type === 'esusu_payout') && grp) {
    if (ctx === 'esusu_rotation') return `Esusu payout — ${grp}${rnd}, your turn`;
    return `Savings group release — ${grp}`;
  }
  if (type === 'group_release' && grp) return `Released from savings group — ${grp}`;
  if (type === 'withdrawal') {
    if (grp) return `From: Released group funds — ${grp}`;
    return `From: Personal Savings${cyc ? ` — ${cyc}` : ''}`;
  }
  if (ctx === 'esusu_rotation')  return `To: Esusu — ${grp}${rnd}`;
  if (ctx === 'group_savings')   return `To: Savings Group — ${grp}`;
  return `To: Personal Savings${cyc ? ` — ${cyc}` : ''}`;
}

export function buildAsoContributionReceipt(contribution, clientName, businessName, recordedByName, biz) {
  const isWithdrawal = contribution.type === 'withdrawal';
  const isReg        = contribution.type === 'registration_fee';
  const status       = contribution.status === 'pending' ? 'pending' : 'success';
  const { ref, hasRef, image, pdf } = receiptFilenames(contribution.id, contribution.created_at || contribution.date, undefined, contribution.receipt_ref);
  const destination  = buildDestinationLabel(contribution);
  const method       = contribution.payment_method ? humanize(contribution.payment_method) : null;
  const balanceAfter = numOrNull(contribution.balance_after);

  return {
    title:     isReg ? 'Registration Fee' : isWithdrawal ? 'Withdrawal' : 'Contribution',
    direction: isWithdrawal ? 'out' : 'in',
    status,
    amount:    contribution.amount,
    datetime:  formatReceiptDateTime(contribution.created_at || contribution.date),
    fields: [
      { label: 'Transaction Type', value: isReg ? 'Registration Fee' : isWithdrawal ? 'Ajo Withdrawal' : 'Ajo Contribution' },
      destination                 && { label: isWithdrawal ? 'From' : 'To',  value: destination },
      clientName                  && { label: 'Member',         value: clientName },
      method                      && { label: 'Payment Method', value: method },
      contribution.notes          && { label: 'Note',           value: contribution.notes },
      recordedByName              && { label: 'Recorded by',    value: recordedByName },
      balanceAfter != null        && { label: 'Balance After',  value: fmtAmt(balanceAfter) },
                                     { label: 'Reference',      value: ref, copy: hasRef },
    ].filter(Boolean),
    businessName,
    issuedBy:      businessName,
    fees:          0,
    receiptRef:    ref,
    filenames:     { image, pdf },
    processorName: null,
    iconType:      'ajo',
    recordedBy:    recordedByName || null,
    ...meta(contribution, { hasRef, method, balanceAfter, biz }),
  };
}

// ── Ajo withdrawal request (from AjoMemberPortal screen) ─────────────────────
export function buildAjoWithdrawalReceipt(req, clientName, businessName) {
  const statusMap = { pending: 'pending', approved: 'success', rejected: 'failed' };
  const { ref, hasRef, image, pdf } = receiptFilenames(req.id, req.requested_at, 'Withdrawal Request', req.receipt_ref);
  const destination = req.group_name
    ? `From: Released group funds — ${req.group_name}`
    : `From: Personal Savings${req.cycle_label ? ` — ${req.cycle_label}` : ''}`;

  return {
    title:     'Withdrawal Request',
    direction: 'out',
    status:    statusMap[req.status] || 'pending',
    amount:    req.net_amount ?? req.amount,
    datetime:  formatReceiptDateTime(req.requested_at),
    fields: [
      { label: 'Transaction Type', value: 'Ajo Withdrawal' },
      destination        && { label: 'From',           value: destination },
      clientName         && { label: 'Member',         value: clientName },
      req.fee_amount > 0 && { label: 'Processing Fee', value: fmtAmt(req.fee_amount) },
      req.fee_type       && { label: 'Fee Type',        value: humanize(req.fee_type) },
                            { label: 'Reference',       value: ref, copy: hasRef },
    ].filter(Boolean),
    businessName,
    issuedBy:      businessName,
    fees:          req.fee_amount || 0,
    receiptRef:    ref,
    filenames:     { image, pdf },
    processorName: null,
    iconType:      'ajo',
    ...meta({ created_at: req.requested_at }, { hasRef }),
  };
}

// ── Debt repayment (from Credit screen) ────────────────────────────────────
export function buildCreditPaymentReceipt(payment, credit, businessName, biz) {
  const { ref, hasRef, image, pdf } = receiptFilenames(payment.id, payment.created_at || payment.payment_date, 'Debt Repayment', payment.receipt_ref);
  // What the debtor still owes after this payment: stored at write time; older
  // payments fall back to the outstanding figure on the credit record.
  const stored = numOrNull(payment.balance_after);
  const remaining = stored != null ? stored
    : (credit?.outstanding != null && payment.amount != null) ? credit.outstanding - payment.amount : null;
  const method = payment.payment_method ? humanize(payment.payment_method) : null;

  return {
    title:     'Debt Repayment',
    direction: 'in',
    status:    'success',
    amount:    payment.amount,
    datetime:  formatReceiptDateTime(payment.created_at || payment.payment_date),
    fields: [
      { label: 'Transaction Type', value: 'Debt Repayment' },
      credit?.customer_name  && { label: 'Customer',          value: credit.customer_name },
      method                 && { label: 'Payment Method',    value: method },
      remaining != null      && { label: 'Remaining Balance', value: fmtAmt(remaining) },
      payment.notes          && { label: 'Note',              value: payment.notes },
                                { label: 'Reference',          value: ref, copy: hasRef },
    ].filter(Boolean),
    businessName,
    issuedBy:      businessName,
    fees:          0,
    receiptRef:    ref,
    filenames:     { image, pdf },
    processorName: null,
    iconType:      'credit',
    ...meta(payment, { hasRef, method, balanceAfter: remaining, balanceLabel: 'Remaining Balance', biz }),
  };
}

// ── Coop savings deposit/withdrawal (from CoopMemberPortal / CoopDashboard) ──
export function buildCoopSavingsReceipt(record, memberName, orgName, biz) {
  const isWithdrawal = record.type === 'withdrawal';
  const { ref, hasRef, image, pdf } = receiptFilenames(record.id, record.created_at, undefined, record.receipt_ref);
  const method = record.payment_method ? humanize(record.payment_method) : null;

  return {
    title:     isWithdrawal ? 'Savings Withdrawal' : 'Savings Deposit',
    direction: isWithdrawal ? 'out' : 'in',
    status:    'success',
    amount:    record.amount,
    datetime:  formatReceiptDateTime(record.created_at),
    fields: [
      { label: 'Transaction Type', value: isWithdrawal ? 'Savings Withdrawal' : 'Savings Deposit' },
      memberName                    && { label: 'Member',         value: memberName },
      method                        && { label: 'Payment Method', value: method },
      record.balance_after != null  && { label: 'Balance After',  value: fmtAmt(record.balance_after) },
                                       { label: 'Reference',      value: ref, copy: hasRef },
    ].filter(Boolean),
    businessName:  orgName,
    issuedBy:      orgName,
    fees:          0,
    receiptRef:    ref,
    filenames:     { image, pdf },
    processorName: null,
    iconType:      'savings',
    ...meta(record, { hasRef, method, balanceAfter: record.balance_after, biz }),
  };
}

// ── Coop withdrawal request (from CoopMemberPortal) ──────────────────────────
export function buildCoopWithdrawalRequestReceipt(request, memberName, orgName) {
  const statusMap = { pending: 'pending', approved: 'success', rejected: 'failed' };
  const { ref, hasRef, image, pdf } = receiptFilenames(request.id, request.created_at, 'Withdrawal Request', request.receipt_ref);

  return {
    title:     'Withdrawal Request',
    direction: 'out',
    status:    statusMap[request.status] || 'pending',
    amount:    request.amount,
    datetime:  formatReceiptDateTime(request.created_at),
    fields: [
      { label: 'Transaction Type', value: 'Savings Withdrawal' },
      memberName       && { label: 'Member',    value: memberName },
      request.reason   && { label: 'Reason',    value: request.reason },
      request.status   && { label: 'Status',    value: humanize(request.status) },
                          { label: 'Reference', value: ref, copy: hasRef },
    ].filter(Boolean),
    businessName:  orgName,
    issuedBy:      orgName,
    fees:          0,
    receiptRef:    ref,
    filenames:     { image, pdf },
    processorName: null,
    iconType:      'savings',
    ...meta(request, { hasRef }),
  };
}

// ── Ajo contribution (logged — from AjoMemberPortal history list) ────────────
// periodSplit: optional { splits: [{idx, amount}] } from allocateForReceipt —
// when provided, adds per-period breakdown rows to the receipt fields.
export function buildAjoContributionReceipt(contribution, clientName, businessName, periodSplit = null, biz) {
  const t        = contribution.type || '';
  const label    = t === 'contribution' ? 'Ajo Contribution'
                 : t === 'withdrawal'   ? 'Ajo Withdrawal'
                 : ledgerTypeLabel(contribution);
  const isOut    = t === 'withdrawal' || t === 'withdrawal_fee' || t === 'registration_fee'
                 || t === 'commission' || t.startsWith('reversal_');
  const statusMap = { completed: 'success', confirmed: 'success', pending: 'pending', rejected: 'failed', declined: 'failed' };
  const { ref, hasRef, image, pdf } = receiptFilenames(contribution.id, contribution.created_at || contribution.date, undefined, contribution.receipt_ref);
  const destination = buildDestinationLabel(contribution);
  const method       = contribution.payment_method ? humanize(contribution.payment_method) : null;
  const balanceAfter = numOrNull(contribution.balance_after);

  const splitFields = (periodSplit?.splits || []).map(s => ({
    label: `  Period ${s.idx + 1}`,
    value: `₦${Number(s.amount).toLocaleString('en-NG')}`,
  }));

  return {
    title:     label,
    direction: isOut ? 'out' : 'in',
    status:    statusMap[contribution.status] || 'pending',
    amount:    contribution.amount,
    datetime:  formatReceiptDateTime(contribution.created_at || contribution.date),
    fields: [
      { label: 'Transaction Type', value: label },
      destination                 && { label: isOut ? 'From' : 'To', value: destination },
      clientName                  && { label: 'Member',         value: clientName },
      splitFields.length > 0      && { label: 'Allocation',     value: `${splitFields.length} period${splitFields.length > 1 ? 's' : ''}` },
      ...splitFields,
      method                      && { label: 'Payment Method', value: method },
      balanceAfter != null        && { label: 'Balance After',  value: fmtAmt(balanceAfter) },
                                     { label: 'Reference',      value: ref, copy: hasRef },
    ].filter(Boolean),
    businessName,
    issuedBy:      businessName,
    fees:          0,
    receiptRef:    ref,
    filenames:     { image, pdf },
    processorName: null,
    iconType:      'ajo',
    ...meta(contribution, { hasRef, method, balanceAfter, biz }),
  };
}

// ── Bill payment (airtime, data, electricity, cable, betting — from BillPayments) ──
// `bill` is the output of billToReceipt() in BillPayments.jsx (already parsed from note).
const BILL_CAT_LABELS = {
  airtime: 'Airtime Top-Up', data: 'Data Bundle', electricity: 'Electricity',
  cable: 'Cable TV', betting: 'Betting Wallet', waec: 'WAEC ePin',
  jamb: 'JAMB ePin', spectranet: 'Spectranet Internet', smile: 'Smile 4G',
  'print-airtime': 'Airtime Print', 'print-data': 'Data Print',
  'airtime-bundle': 'Airtime Bundle',
};
export function buildBillReceipt(bill) {
  const businessName = bill.businessName || 'My Business';
  const title = BILL_CAT_LABELS[bill.category] || (bill.category ? humanize(bill.category) : '') || 'Bill Payment';
  const { ref, hasRef, image, pdf } = receiptFilenames(bill.id, bill.created_at || bill.transaction_date, title, bill.receipt_ref);
  // Who actually took the payment — read from the record, never assumed. A legacy
  // bill that never recorded its funding source shows no processor at all.
  const processor    = processorFor(billPaidVia(bill));
  const balanceAfter = numOrNull(bill.balance_after);
  // Electricity: name the DISCO from whatever the record carries ("EKEDC (Eko) Prepaid", a full company name, or the
  // company code the payment webhook stores) so every electricity receipt — older ones included — shows its DISCO's logo.
  const disco = bill.category === 'electricity' ? discoFromRecord(bill) : null;
  // Cable / betting / exam pins / internet: the same idea — name the provider from whatever the record carries ("DSTV", the
  // webhook's "dstv" / "product-bang-bet", the note) so every receipt, older ones included, shows its provider's logo.
  const brand = billBrandFromRecord(bill);

  const fields = [
    { label: 'Transaction Type', value: title },
    bill.network      && { label: 'Network',      value: bill.network },
    bill.phone        && { label: 'Phone',         value: bill.phone },
    bill.planName     && { label: 'Plan',          value: bill.planName },
    bill.smartcard    && { label: 'Smartcard No.', value: bill.smartcard },
    bill.meterNo      && { label: 'Meter No.',     value: bill.meterNo },
    bill.meterAddress && { label: 'Address',       value: bill.meterAddress },
    bill.meterTypeName && { label: 'Meter Type',   value: bill.meterTypeName },
    (bill.providerName || disco) && { label: 'Provider', value: (bill.category === 'cable' && brand?.name) || bill.providerName || DISCO_LABELS[disco] || disco },
    bill.category === 'betting' && brand && { label: 'Platform', value: brand.name },
    bill.packageName  && { label: 'Package',       value: bill.packageName },
    bill.customerId   && { label: 'Customer ID',   value: bill.customerId },
    // electricity token — present value or mark as retrievable
    bill.category === 'electricity' && {
      label:       'Token',
      value:       bill.token || (bill.apiRef ? null : '—'),
      retrievable: !bill.token && !!bill.apiRef,
      orderId:     bill.apiRef,
    },
    bill.cardDetails && { label: 'Card Details', value: bill.cardDetails },
    bill.pinsArr?.length > 0 && {
      label: 'Pins Issued',
      value: `${bill.pinsArr.length} token${bill.pinsArr.length > 1 ? 's' : ''} (tap PDF to view)`,
    },
    bill.apiRef && { label: 'Provider Ref.', value: bill.apiRef, copy: true },
    bill.staffName && { label: 'Served by',   value: bill.staffName },
    processor      && { label: 'Payment Method', value: processor.label },
    // the running balance is for the owner, in the app — it never goes out with a shared image / PDF (see PRIVATE ROWS)
    balanceAfter != null && { label: 'Balance After', value: fmtAmt(balanceAfter), private: true },
    { label: 'Reference',     value: ref, copy: hasRef },
  ].filter(Boolean);

  return {
    title,
    direction:    'out',
    status:       bill.bill_status === 'failed' ? 'failed' : 'success',
    amount:       bill.amount,
    datetime:     formatReceiptDateTime(bill.created_at || bill.transaction_date),
    fields,
    businessName,
    issuedBy:     businessName,
    fees:         0,
    receiptRef:   ref,
    filenames:    { image, pdf },
    provider:      disco || brand?.name || bill.network || bill.providerName || bill.platformName || null,
    category:      bill.category || null,
    processorName: processor?.label || null,
    processorLine: processor?.line  || null,
    iconType:      null,
    recordedBy:    bill.staffName || null,
    ...meta(bill, { hasRef, method: processor?.label, balanceAfter, biz: { address: bill.businessAddress, phone: bill.businessPhone } }),
    hideBalanceOnShare: true,
    // Raw structured data for specialized display in TransactionDetailModal
    elecToken:    bill.token      || undefined,
    cardDetails:  bill.cardDetails || undefined,
    pinsArr:      bill.pinsArr?.length > 0 ? bill.pinsArr : undefined,
  };
}

// ── Credit/loan statement (from Credit screen — tap "Statement" on a record) ──
export function buildCreditStatementReceipt(credit, businessName, biz) {
  const { image, pdf } = receiptFilenames(credit.id, credit.created_at, 'Credit Statement');
  const statusMap = { active: 'pending', overdue: 'failed', settled: 'success' };

  return {
    title:     'Credit Statement',
    direction: 'out',
    status:    statusMap[credit.status] || 'pending',
    amount:    credit.outstanding || 0,
    datetime:  formatReceiptDateTime(credit.created_at),
    fields: [
      { label: 'Transaction Type', value: 'Credit Statement' },
      credit.customer_name && { label: 'Customer',     value: credit.customer_name },
      credit.phone         && { label: 'Phone',         value: credit.phone },
      credit.item_name     && { label: 'Item / Purpose', value: credit.item_name },
      { label: 'Total Given',   value: fmtAmt(credit.amount_given || credit.amount || 0) },
      { label: 'Total Repaid',  value: fmtAmt(credit.total_paid || 0) },
      { label: 'Outstanding',   value: fmtAmt(credit.outstanding || 0) },
      credit.due_date && { label: 'Due Date', value: formatReceiptDateTime(credit.due_date) },
      credit.status && { label: 'Status', value: humanize(credit.status) },
    ].filter(Boolean),
    businessName,
    issuedBy:      businessName,
    fees:          0,
    receiptRef:    null,
    filenames:     { image, pdf },
    processorName: null,
    iconType:      'statement',
    kind:          'statement',
    ...meta(credit, { hasRef: false, balanceAfter: credit.outstanding || 0, balanceLabel: 'Outstanding', biz }),
  };
}

// ── Ajo/Aso client savings statement (from Aso screen — tap "Statement" on a client) ──
export function buildAsoClientReceipt(client, businessName, biz) {
  const { image, pdf } = receiptFilenames(client.id, new Date().toISOString(), 'Ajo Member Statement');
  const generatedAt = new Date().toISOString();

  return {
    title:     'Ajo Member Statement',
    direction: 'in',
    status:    'success',
    amount:    client.current_balance || 0,
    datetime:  formatReceiptDateTime(generatedAt),
    fields: [
      { label: 'Transaction Type', value: 'Ajo Member Statement' },
      client.full_name && { label: 'Member', value: client.full_name },
      client.phone     && { label: 'Phone',  value: client.phone },
      { label: 'Total Deposited',   value: fmtAmt(client.total_saved || 0) },
      { label: 'Total Withdrawn',  value: fmtAmt(client.total_withdrawn || 0) },
      { label: 'Current Balance',  value: fmtAmt(client.current_balance || 0) },
      client.contribution_amount && {
        label: 'Contribution',
        value: fmtAmt(client.contribution_amount) + (client.contribution_frequency ? ` / ${client.contribution_frequency}` : ''),
      },
      client.joined_at && { label: 'Member Since', value: formatReceiptDateTime(client.joined_at) },
    ].filter(Boolean),
    businessName,
    issuedBy:      businessName,
    fees:          0,
    receiptRef:    null,
    filenames:     { image, pdf },
    processorName: null,
    iconType:      'statement',
    kind:          'statement',
    ...meta({ created_at: generatedAt }, { hasRef: false, balanceAfter: client.current_balance || 0, balanceLabel: 'Current Balance', biz }),
  };
}

// ── Coop/Org loan repayment (from CoopDashboard & CoopMemberPortal LoansTab) ──
export function buildCoopLoanRepaymentReceipt(repayment, loan, memberName, orgName, biz) {
  const { ref, hasRef, image, pdf } = receiptFilenames(repayment.id, repayment.created_at, 'Loan Repayment', repayment.receipt_ref);
  const method = repayment.payment_method ? humanize(repayment.payment_method) : null;
  return {
    title:     'Loan Repayment',
    direction: 'in',
    status:    'success',
    amount:    repayment.amount,
    datetime:  formatReceiptDateTime(repayment.created_at),
    fields: [
      { label: 'Transaction Type',   value: 'Loan Repayment' },
      memberName                        && { label: 'Member',            value: memberName },
      loan?.loan_purpose                && { label: 'Loan Purpose',      value: loan.loan_purpose },
      repayment.principal_portion > 0   && { label: 'Principal Paid',    value: fmtAmt(repayment.principal_portion) },
      repayment.interest_portion  > 0   && { label: 'Interest Paid',     value: fmtAmt(repayment.interest_portion) },
      method                            && { label: 'Payment Method',    value: method },
      loan?.outstanding_balance != null && { label: 'Remaining Balance', value: fmtAmt(loan.outstanding_balance) },
                                           { label: 'Reference',         value: ref, copy: hasRef },
    ].filter(Boolean),
    businessName:  orgName,
    issuedBy:      orgName,
    fees:          0,
    receiptRef:    ref,
    filenames:     { image, pdf },
    processorName: null,
    iconType:      'savings',
    ...meta(repayment, { hasRef, method, balanceAfter: loan?.outstanding_balance, balanceLabel: 'Remaining Balance', biz }),
  };
}

// ── Wallet ledger entry (from the Wallet screen — tap a transaction) ─────────
// Flutterwave returns e.g. "Flutterwave MFB (Formerly OK MFB)" — drop the aside.
export const cleanBankName = (n) =>
  String(n || '').replace(/\s*\((?:formerly|former|prev\.?|previously)[^)]*\)/i, '').trim();

export const WALLET_TITLES = {
  topup:               'Wallet Funding',
  sale:                'Payment Received',
  bill_spend:          'Bill Payment',
  bill_reversal:       'Bill Refund',
  subscription_spend:  'Plan Upgrade',
  subscription_reversal: 'Plan Refund',
  withdrawal:          'Transfer',
  withdrawal_reversal: 'Transfer Refund',
  adjustment:          'Wallet Adjustment',
  transfer_fee:        'Transfer Fee',
  cbn_levy:            'CBN Electronic Transfer Levy',
};

// A two-line "Name / Bank • Account" value, OPay-receipt style. ReceiptCard
// renders the first line prominent and the rest muted.
function party(name, bank, account) {
  const head = String(name || '').trim() || '—';
  const tail = [bank, account].map((s) => String(s || '').trim()).filter(Boolean).join('  •  ');
  return tail ? `${head}\n${tail}` : head;
}

// Business + owner identity only — no account number. Used for "who sent
// this" on an outbound receipt (transfer, bill payment), where the wallet
// account used to send is deliberately left off.
function senderIdentity(businessName, ownerName) {
  const head = String(businessName || '').trim() || '—';
  const sub  = String(ownerName || '').trim();
  return sub && sub.toLowerCase() !== head.toLowerCase() ? `${head}\n${sub}` : head;
}

// ctx (all optional): businessName, ownerName, walletAccountNumber,
//   withdrawal (wallet_withdrawals row), request (wallet_payment_requests row),
//   originator (deposit sender name), originatorBank (the sender's bank on a deposit / payment received),
//   recipientBankName (resolved from bank_code)
//
// PRIVATE ROWS — a field flagged `private: true` (the running balance on a bill or wallet receipt) is shown in the app but
// left off everything that leaves it: ReceiptCard marks it data-private (stripped from the shared image by
// captureReceiptCanvas) and the PDF layout skips it. `hideBalanceOnShare` tells the PDF not to print its own balance row.
export function buildWalletReceipt(row, ctx = {}) {
  const credit = row.direction === 'credit';
  const src    = row.source;
  const title  = WALLET_TITLES[src] || humanize(src);
  const status = row.status === 'pending' || row.status === 'processing' ? 'pending'
               : row.status === 'reversed' || row.status === 'failed' ? 'failed'
               : 'success';
  const { ref, hasRef, image, pdf } = receiptFilenames(row.id, row.created_at, title, row.receipt_ref);
  const amount = (row.amount_kobo || 0) / 100;

  // The business's own side of every wallet movement — the receipt shows the
  // business name (not the BVN name or the "Flutterwave MFB" bank behind the VA).
  const businessName = ctx.businessName || 'My Business';
  const walletAcct   = ctx.walletAccountNumber || '';
  const walletParty  = party(businessName, 'KudiAI Wallet', walletAcct);
  const sender       = senderIdentity(businessName, ctx.ownerName);
  const wd           = ctx.withdrawal || null;
  const rq           = ctx.request || null;
  const narration    = (wd?.narration || row.narration || '').trim();
  // The wallet's running balance is for its owner, in the app — never on a shared image / PDF (see PRIVATE ROWS)
  const balRow = row.balance_after_kobo != null && { label: 'Account balance after', value: fmtAmt(row.balance_after_kobo / 100), private: true };

  // The bank on the OTHER side of the movement — where a transfer went, or where a deposit / payment came from.
  // It names the bank in the party rows and gives the receipt its logo. Unknown banks still get a name, just no logo.
  let counterparty = null;
  const withCounterparty = (role, bank) => { counterparty = bank ? { role, bank: bank.name, logoUrl: bank.logoUrl, initials: bank.initials } : null; return bank; };

  // Sending money out (transfer, bill payment) names the business and owner,
  // but never the wallet account that sent it. Receiving (funding, a sale)
  // still shows where it landed, account included.
  let fields;
  if (src === 'withdrawal' || src === 'withdrawal_reversal') {
    const bankInfo = describeBank({ code: wd?.bank_code, name: ctx.recipientBankName || cleanBankName(wd?.bank_name) });
    if (src === 'withdrawal') withCounterparty('recipient', bankInfo);
    const rcptBank = bankInfo?.name || wd?.bank_code || '';
    fields = [
      { label: 'Transaction Type', value: src === 'withdrawal_reversal' ? 'Transfer reversal — refunded to wallet' : 'Wallet transfer' },
      { label: 'Recipient Details', value: party(wd?.account_name || narration || 'Bank account', rcptBank, wd?.account_number) },
      { label: 'Sender Details',    value: sender },
      narration && !/^transfer to bank$/i.test(narration) && { label: 'Narration', value: narration },
      wd?.fee_kobo ? { label: 'Fee', value: fmtAmt(wd.fee_kobo / 100) } : null,
      wd?.flw_transfer_id && { label: 'Transaction No.', value: wd.flw_transfer_id, copy: true },
      wd?.session_id      && { label: 'Session ID',      value: wd.session_id, copy: true },
      balRow,
      { label: 'Payment Method', value: 'KudiAI Wallet' },
      { label: 'Status',    value: humanize(row.status) },
      { label: 'Reference', value: ref, copy: hasRef },
    ];
  } else if (src === 'topup') {
    const grossKobo = row.meta?.gross_amount_kobo;
    const feeKobo    = row.meta?.fee_kobo;
    const fromBank   = withCounterparty('sender', describeBank({ name: ctx.originatorBank }));
    fields = [
      { label: 'Transaction Type', value: 'Wallet funding (bank transfer)' },
      { label: 'Recipient Details', value: walletParty },
      { label: 'Sender Details',    value: party(ctx.originator || 'Bank transfer', fromBank?.name, '') },
      grossKobo > 0 && { label: 'Amount received', value: fmtAmt(grossKobo / 100) },
      feeKobo > 0    && { label: 'CBN electronic transfer levy', value: fmtAmt(feeKobo / 100) },
      row.flw_reference && { label: 'Transaction No.', value: row.flw_reference, copy: true },
      balRow,
      { label: 'Payment Method', value: 'Bank transfer' },
      { label: 'Status',    value: humanize(row.status) },
      { label: 'Reference', value: ref, copy: hasRef },
    ];
  } else if (src === 'sale') {
    const note = (rq?.note || narration || '').replace(/^Sale —\s*/i, '').trim();
    const fromBank = withCounterparty('sender', describeBank({ name: ctx.originatorBank }));
    fields = [
      { label: 'Transaction Type', value: 'Payment received' },
      { label: 'Recipient Details', value: walletParty },
      { label: 'Sender Details',    value: party(rq?.customer_name || ctx.originator || 'Customer', fromBank?.name, '') },
      note && { label: 'For', value: note },
      row.flw_reference && { label: 'Transaction No.', value: row.flw_reference, copy: true },
      balRow,
      { label: 'Payment Method', value: 'Bank transfer' },
      { label: 'Status',    value: humanize(row.status) },
      { label: 'Reference', value: ref, copy: hasRef },
    ];
  } else if (src === 'bill_spend' || src === 'bill_reversal') {
    fields = [
      { label: 'Transaction Type', value: src === 'bill_reversal' ? 'Bill refund — credited to wallet' : 'Bill payment' },
      narration && { label: src === 'bill_reversal' ? 'Refund for' : 'Paid for', value: narration },
      src === 'bill_reversal' ? { label: 'Credited to', value: walletParty } : { label: 'Paid by', value: sender },
      row.flw_reference && { label: 'Provider Ref.', value: row.flw_reference, copy: true },
      balRow,
      { label: 'Payment Method', value: 'KudiAI Wallet' },
      { label: 'Status',    value: humanize(row.status) },
      { label: 'Reference', value: ref, copy: hasRef },
    ];
  } else if (src === 'subscription_spend' || src === 'subscription_reversal') {
    fields = [
      { label: 'Transaction Type', value: src === 'subscription_reversal' ? 'Subscription refund — credited to wallet' : 'Subscription payment' },
      narration && { label: src === 'subscription_reversal' ? 'Refund for' : 'Paid for', value: narration },
      src === 'subscription_reversal' ? { label: 'Credited to', value: walletParty } : { label: 'Paid by', value: sender },
      balRow,
      { label: 'Payment Method', value: 'KudiAI Wallet' },
      { label: 'Status',    value: humanize(row.status) },
      { label: 'Reference', value: ref, copy: hasRef },
    ];
  } else {
    fields = [
      { label: 'Transaction Type', value: title },
      { label: credit ? 'Money in' : 'Money out', value: fmtAmt(amount) },
      narration && { label: 'Details', value: narration },
      balRow,
      { label: 'Status',    value: humanize(row.status) },
      { label: 'Reference', value: ref, copy: hasRef },
    ];
  }

  return {
    title,
    direction: credit ? 'in' : 'out',
    status,
    amount,
    datetime:  formatReceiptDateTime(row.created_at),
    fields:    fields.filter(Boolean),
    businessName,
    issuedBy:      businessName,
    fees:          wd?.fee_kobo ? wd.fee_kobo / 100 : row.meta?.fee_kobo ? row.meta.fee_kobo / 100 : 0,
    receiptRef:    ref,
    filenames:     { image, pdf },
    processorName: 'KudiAI Track',
    iconType:      credit ? 'income' : 'expense',
    counterparty,
    hideBalanceOnShare: true,
    ...meta(row, {
      hasRef,
      method:       (src === 'topup' || src === 'sale') ? 'Bank transfer' : 'KudiAI Wallet',
      balanceAfter: row.balance_after_kobo != null ? row.balance_after_kobo / 100 : null,
      balanceLabel: 'Account Balance After',
      biz:          { address: ctx.businessAddress, phone: ctx.businessPhone },
    }),
  };
}
